In [2]:
import sqlite3

conn = sqlite3.connect("library.db")
cur = conn.cursor()

In [4]:
cur.execute("""
CREATE TABLE books (
    book_id INTEGER PRIMARY KEY,
    title   TEXT,
    author  TEXT,
    year    INTEGER
    )
""")

### 데이터 넣기 - Insert

In [ ]:
book_list = [
    (1, "듄", "프랭크 허버트", 2021),
    (2, "은하수를 여행하는 히치하이커를 위한 안내서", "더글러스 애덤스", 1979),
    (3, "노르웨이의 숲", "무라카미 하루키", 1987),
    (4, "나미야 잡화점의 기적", "히가시노 게이고", 2012),
    (5, "더 기버", "로이스 로리", 1993)
]

cur.executemany("INSERT INTO books VALUES (?, ?, ?, ?)", book_list) # 물음표 4개인 이유: 카테고리가 4개라서
conn.commit()

### 데이터 조회하기 - SELECT

In [ ]:
import pandas as pd

df = pd.read_sql("SELECT * FROM books", conn)   # 이제는 read_sql인 것 주목
df

   book_id                    title    author  year
0        1                        듄   프랭크 허버트  2021
1        2  은하수를 여행하는 히치하이커를 위한 안내서  더글러스 애덤스  1979
2        3                  노르웨이의 숲  무라카미 하루키  1987
3        4              나미야 잡화점의 기적  히가시노 게이고  2012
4        5                     더 기버    로이스 로리  1993

In [9]:
df_partial = pd.read_sql("SELECT title, author FROM books", conn)   # 이렇게 일부 카테고리만 가져올 수도 있다!
df_partial

                     title    author
0                        듄   프랭크 허버트
1  은하수를 여행하는 히치하이커를 위한 안내서  더글러스 애덤스
2                  노르웨이의 숲  무라카미 하루키
3              나미야 잡화점의 기적  히가시노 게이고
4                     더 기버    로이스 로리

In [ ]:
# 몇년도 이후 데이터 가져오는 방법

df_filtered = pd.read_sql(
    "SELECT * FROM books WHERE year > ?", conn, # 여기서는 들어갈 변수가 년도 하나밖에 없어서 물음표 하나
    params=(2000,)
)
df_filtered

   book_id        title    author  year
0        1            듄   프랭크 허버트  2021
1        4  나미야 잡화점의 기적  히가시노 게이고  2012

### 조회
- WHERE : 조건으로 행을 찾는 방법
- ORDER BY : 정렬 - 내림차순, 오름차순
- 집계함수 : 개수, 합계, 평균
- GROUP BY : 그룹별로 나눠서 집계

In [15]:
# 데이터 추가하기!

more_books = [
      (6, "해리 포터와 마법사의 돌", "J.K. 롤링", 1997),
      (7, "반지의 제왕", "J.R.R. 톨킨", 1954),
      (8, "어린 왕자", "앙투안 드 생텍쥐페리", 1943),
      (9, "1984", "조지 오웰", 1949),
      (10, "동물 농장", "조지 오웰", 1945),
      (11, "위대한 개츠비", "F. 스콧 피츠제럴드", 1925),
      (12, "오만과 편견", "제인 오스틴", 1813),
      (13, "죄와 벌", "표도르 도스토옙스키", 1866),
      (14, "데미안", "헤르만 헤세", 1919),
      (15, "아몬드", "손원평", 2017),
      (16, "82년생 김지영", "조남주", 2016),
      (17, "완득이", "김려령", 2008),
      (18, "불편한 편의점", "김호연", 2021),
      (19, "달러구트 꿈 백화점", "이미예", 2020),
      (20, "지구 끝의 온실", "김초엽", 2021),
      (21, "모모", "미하엘 엔데", 1973),
      (22, "연금술사", "파울로 코엘료", 1988),
      (23, "사피엔스", "유발 하라리", 2011),
      (24, "침묵의 봄", "레이첼 카슨", 1962),
      (25, "총, 균, 쇠", "재레드 다이아몬드", 1997)
  ]

cur.executemany(
    "INSERT INTO books VALUES (?, ?, ?, ?)", more_books
)

IntegrityError: UNIQUE constraint failed: books.book_id

In [16]:
conn.commit()

In [18]:
df = pd.read_sql("SELECT * FROM books", conn)   # 이제는 read_sql인 것 주목
df

    book_id                    title       author  year
0         1                        듄      프랭크 허버트  2021
1         2  은하수를 여행하는 히치하이커를 위한 안내서     더글러스 애덤스  1979
2         3                  노르웨이의 숲     무라카미 하루키  1987
3         4              나미야 잡화점의 기적     히가시노 게이고  2012
4         5                     더 기버       로이스 로리  1993
5         6            해리 포터와 마법사의 돌      J.K. 롤링  1997
6         7                   반지의 제왕    J.R.R. 톨킨  1954
7         8                    어린 왕자  앙투안 드 생텍쥐페리  1943
8         9                     1984        조지 오웰  1949
9        10                    동물 농장        조지 오웰  1945
10       11                  위대한 개츠비  F. 스콧 피츠제럴드  1925
11       12                   오만과 편견       제인 오스틴  1813
12       13                     죄와 벌   표도르 도스토옙스키  1866
13       14                      데미안       헤르만 헤세  1919
14       15                      아몬드          손원평  2017
15       16                 82년생 김지영          조남주  2016
16       17                      완득이          김려령  2008
17       18                  불편한 편의점          김호연  2021
18       19               달러구트 꿈 백화점          이미예  2020
19       20                 지구 끝의 온실          김초엽  2021
20       21                       모모       미하엘 엔데  1973
21       22                     연금술사      파울로 코엘료  1988
22       23                     사피엔스       유발 하라리  2011
23       24                    침묵의 봄       레이첼 카슨  1962
24       25                  총, 균, 쇠    재레드 다이아몬드  1997

#### (1) WHERE로 조건에 맞는 행 찾기

In [19]:
data = pd.read_sql(
    "SELECT * FROM books WHERE year > 2000", conn, # 이렇게 params 안쓰고 바로 넣어도 됨!
)
data

   book_id        title    author  year
0        1            듄   프랭크 허버트  2021
1        4  나미야 잡화점의 기적  히가시노 게이고  2012
2       15          아몬드       손원평  2017
3       16     82년생 김지영       조남주  2016
4       17          완득이       김려령  2008
5       18      불편한 편의점       김호연  2021
6       19   달러구트 꿈 백화점       이미예  2020
7       20     지구 끝의 온실       김초엽  2021
8       23         사피엔스    유발 하라리  2011

In [20]:
# 조건이 여러개인 것 확인
# AND, OR

data = pd.read_sql("SELECT * FROM books WHERE author = '조지 오웰' AND year > 1945", conn)
data

   book_id title author  year
0        9  1984  조지 오웰  1949

In [21]:
## 부분 검색, 목록 - LIKE, IN
# LIKE : 패턴을 포함하고 있는 데이터 가져오기
# IN : 목록 중에 하나인 것

data_like = pd.read_sql("SELECT * FROM books WHERE title LIKE '%왕자%'", conn)
data_like

   book_id  title       author  year
0        8  어린 왕자  앙투안 드 생텍쥐페리  1943

In [22]:
data_in = pd.read_sql("SELECT * FROM books WHERE year IN (2020, 2021)", conn)
data_in

   book_id       title   author  year
0        1           듄  프랭크 허버트  2021
1       18     불편한 편의점      김호연  2021
2       19  달러구트 꿈 백화점      이미예  2020
3       20    지구 끝의 온실      김초엽  2021

#### ORDER BY - 정렬하기

In [ ]:
pd.read_sql("SELECT * FROM books ORDER BY year DESC LIMIT 10", conn) # 내림차순

   book_id          title    author  year
0        1              듄   프랭크 허버트  2021
1       18        불편한 편의점       김호연  2021
2       20       지구 끝의 온실       김초엽  2021
3       19     달러구트 꿈 백화점       이미예  2020
4       15            아몬드       손원평  2017
5       16       82년생 김지영       조남주  2016
6        4    나미야 잡화점의 기적  히가시노 게이고  2012
7       23           사피엔스    유발 하라리  2011
8       17            완득이       김려령  2008
9        6  해리 포터와 마법사의 돌   J.K. 롤링  1997

In [25]:
pd.read_sql("SELECT * FROM books ORDER BY year ASC LIMIT 10", conn) # 오름차순

   book_id    title       author  year
0       12   오만과 편견       제인 오스틴  1813
1       13     죄와 벌   표도르 도스토옙스키  1866
2       14      데미안       헤르만 헤세  1919
3       11  위대한 개츠비  F. 스콧 피츠제럴드  1925
4        8    어린 왕자  앙투안 드 생텍쥐페리  1943
5       10    동물 농장        조지 오웰  1945
6        9     1984        조지 오웰  1949
7        7   반지의 제왕    J.R.R. 톨킨  1954
8       24    침묵의 봄       레이첼 카슨  1962
9       21       모모       미하엘 엔데  1973

#### 집계함수
- 수치데이터가 있을 경우 집계

In [26]:
# 집계함수를 위한 테이블을 새로 하나 만들어봅시다.
# 집계 연습에 적합한 열을 포함해 테이블 생성
cur.execute("""
CREATE TABLE books_test (
    book_id INTEGER PRIMARY KEY,
    title   TEXT,
    author  TEXT,
    year    INTEGER,
    genre   TEXT,
    pages   INTEGER,
    price   INTEGER,
    rating  REAL
)
""")

book_list = [
    (1, "듄", "프랭크 허버트", 2021, "SF", 688, 18000, 4.8),
    (2, "은하수를 여행하는 히치하이커를 위한 안내서", "더글러스 애덤스", 1979, "SF", 320, 14000, 4.5),
    (3, "노르웨이의 숲", "무라카미 하루키", 1987, "소설", 572, 16000, 4.3),
    (4, "나미야 잡화점의 기적", "히가시노 게이고", 2012, "소설", 456, 15000, 4.6),
    (5, "더기버", "로이스 로리", 1993, "청소년", 280, 12000, 4.2),
    (6, "해리 포터와 마법사의 돌", "J.K. 롤링", 1997, "판타지", 320, 15000, 4.9),
    (7, "반지의 제왕", "J.R.R. 톨킨", 1954, "판타지", 980, 25000, 4.8),
    (8, "어린 왕자", "앙투안 드 생텍쥐페리", 1943, "동화", 120, 9000, 4.7),
    (9, "1984", "조지 오웰", 1949, "소설", 360, 13000, 4.6),
    (10, "동물 농장", "조지 오웰", 1945, "소설", 180, 10000, 4.4),
    (11, "위대한 개츠비", "F. 스콧 피츠제럴드", 1925, "소설", 240, 11000, 4.1),
    (12, "오만과 편견", "제인 오스틴", 1813, "소설", 480, 14000, 4.5),
    (13, "죄와 벌", "도스토옙스키", 1866, "소설", 720, 19000, 4.4),
    (14, "데미안", "헤르만 헤세", 1919, "소설", 220, 11000, 4.3),
    (15, "아몬드", "손원평", 2017, "청소년", 260, 13000, 4.6),
    (16, "82년생 김지영", "조남주", 2016, "소설", 190, 12000, 4.2),
    (17, "완득이", "김려령", 2008, "청소년", 240, 12000, 4.4),
    (18, "불편한 편의점", "김호연", 2021, "소설", 270, 14000, 4.5),
    (19, "달러구트 꿈 백화점", "이미예", 2020, "판타지", 300, 14000, 4.6),
    (20, "지구 끝의 온실", "김초엽", 2021, "SF", 390, 16000, 4.7),
    (21, "모모", "미하엘 엔데", 1973, "판타지", 350, 13000, 4.8),
    (22, "연금술사", "파울로 코엘료", 1988, "소설", 280, 12000, 4.3),
    (23, "사피엔스", "유발 하라리", 2011, "역사", 640, 22000, 4.7),
    (24, "침묵의 봄", "레이첼 카슨", 1962, "과학", 400, 18000, 4.5),
    (25, "총, 균, 쇠", "재레드 다이아몬드", 1997, "역사", 720, 24000, 4.6)
]

cur.executemany("""
INSERT INTO books_test
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
""", book_list)

conn.commit()

함수 종류
- count
- sum
- avg
- max, min

In [ ]:
# 장르별 책 수를 합쳐 '책 수'라는 카테고리에 저장. genre도 '장르'라는 컬럼으로
# 문법: 일단 AS 뒤엔 따옴표 X, 그리고 함수들은 쉼표 안 쓰는듯

data = pd.read_sql("""
SELECT genre AS 장르,
COUNT(*) AS 책수    
FROM books_test
GROUP BY genre
""", conn)


data

    장르  책수
0   SF   3
1   과학   1
2   동화   1
3   소설  11
4   역사   2
5  청소년   3
6  판타지   4

In [ ]:
# 장르별 책 수를 합쳐 '책 수'라는 카테고리에 저장. genre도 '장르'라는 컬럼으로
# 쉼표 있고 없고 기준 : 한 함수(SELECT, FROM 등) 안에 여러 개 들어가면 쉼표로 구분, 함수와 함수 사이에는 쉼표 X

data = pd.read_sql("""
SELECT genre AS 장르,
    COUNT(*) AS 책수,
    AVG(PRICE) AS 평균가격
FROM books_test
GROUP BY genre
ORDER BY 책수
""", conn)

data

    장르  책수          평균가격
0   과학   1  18000.000000
1   동화   1   9000.000000
2   역사   2  23000.000000
3   SF   3  16000.000000
4  청소년   3  12333.333333
5  판타지   4  16750.000000
6   소설  11  13363.636364