### 조회와 선택
- 원하는 열과 행을 꺼내는 방법 익히기
- 조건 걸어서 해보기
- 특정 열과 행을 선택해서 처리해야 하는 경우가 대부분

In [20]:
import pandas as pd

In [21]:
# 상위 폴더로 가려면 ../ 치면 된다!

df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

#### 1. 열 하나 선택
- df['열 이름']

In [22]:
df['이름']  # 기본적으로 데이터가 딕셔너리 형태였던 것 기억하면, 이렇게 불러오는 것 이해 가능

0    김민준
1    이서연
2    박도윤
3    최지우
4    정하준
5    이서연
Name: 이름, dtype: str

#### 2. 여러 열 선택
- df[['열1', '열2']]

In [23]:
df[['영어', '국어', '수학']]    # 순서도 반영된다

     영어    국어   수학
0  80.0  90.0  100
1  92.0  85.0   78
2  75.0   NaN   88
3   NaN  70.0   65
4  95.0  88.0   결석
5  92.0  85.0   78

#### 3. 행 선택 - loc(이름표로 찾기)
- loc 행의 인덱스 라벨명으로 행을 꺼냅니다
- 지금 위의 데이터에서는 라벨명이 0,1,2,...

In [24]:
df.loc[0]

이름     김민준
반        A
성별       남
국어    90.0
영어    80.0
수학     100
Name: 0, dtype: object

In [ ]:
df.loc[1:3] # 1~2번째가 아니라, '이름'으로 하므로 1~3까지 다 뜸 (슬라이싱과 다르다!!)

    이름  반 성별    국어    영어  수학
1  이서연  B  여  85.0  92.0  78
2  박도윤  A  남   NaN  75.0  88
3  최지우  B  여  70.0   NaN  65

In [26]:
# 인덱스 0~5 아닌 경우도 많음
df.index = ["A", "B", "C", "D", "E", "F"]
df

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78

In [27]:
df.loc['A']

이름     김민준
반        A
성별       남
국어    90.0
영어    80.0
수학     100
Name: A, dtype: object

In [28]:
df.loc["B":"D"]

    이름  반 성별    국어    영어  수학
B  이서연  B  여  85.0  92.0  78
C  박도윤  A  남   NaN  75.0  88
D  최지우  B  여  70.0   NaN  65

In [31]:
df.loc["B":"D"][["국어", "수학", "영어"]]

     국어  수학    영어
B  85.0  78  92.0
C   NaN  88  75.0
D  70.0  65   NaN

In [ ]:
df.loc["B":"D", ["국어", "수학", "영어"]]   # 옆에 두지 말고 쉼표 찍고 안에 넣어도 된다!

     국어  수학    영어
B  85.0  78  92.0
C   NaN  88  75.0
D  70.0  65   NaN

#### 4. 행 선택 - iloc (순서번호로 찾기)
- 우리가 알던 인덱싱, 슬라이싱!
- 몇 번째인지 순서로 꺼냄

In [29]:
df.iloc[0]

이름     김민준
반        A
성별       남
국어    90.0
영어    80.0
수학     100
Name: A, dtype: object

In [ ]:
df.iloc[1:3]    # 슬라이싱과 같으므로, 1~2까지만 나온다!

    이름  반 성별    국어    영어  수학
B  이서연  B  여  85.0  92.0  78
C  박도윤  A  남   NaN  75.0  88

In [ ]:
df.iloc[1:3, 2:4]   # 첫 번째는 행 슬라이싱, 쉼표 찍고 열 슬라이싱도 할 수 있다!

  성별    국어
B  여  85.0
C  남   NaN

#### 5. 조건으로 데이터 가져오기
- 비교식을 대괄호 안에 넣으면 조건이 참인 행만 고를 수 있다

In [33]:
df.head()

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석

In [35]:
# 이 결과가 하나의 Series로 나온다! 즉 참/거짓을 순서대로 담은 Series
mask = df['성별'] == "남"
mask

A     True
B    False
C     True
D    False
E     True
F    False
Name: 성별, dtype: bool

In [36]:
df[mask]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
C  박도윤  A  남   NaN  75.0   88
E  정하준  A  남  88.0  95.0   결석

In [39]:
# 바로 작성도 가능
df[df["국어"] >= 85]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78

In [ ]:
df[df["수학"] >= 80]

# 결과는 에러 뜬다! 수학 점수에 "결석" 이라는 값 있기 때문... -> 전처리의 필요성!

TypeError: '>=' not supported between instances of 'str' and 'int'

#### 6. 여러 조건 - &(그리고), |(또는)
- 조건이 여러 개면 &, | 적절히 사용
- 각 조건은 소괄호로 감사야 함!

In [43]:
# A 반이면서 국어가 85점 이상인 학생만
mask = (df["반"] == "A") & (df["국어"] >= 85)

df[mask]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
E  정하준  A  남  88.0  95.0   결석

In [46]:
# 연습 1- 성별이 여자면서 영어 점수가 90점 이상

mask = (df["성별"] == "여") & (df["영어"] >= 90)

df[mask]

    이름  반 성별    국어    영어  수학
B  이서연  B  여  85.0  92.0  78
F  이서연  B  여  85.0  92.0  78

In [ ]:
# 연습 2 - 성별 여자거나 국어 80점 이상

mask = (df["성별"] == "여") | (df["국어"] >= 80)
df[mask]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78