### 데이터 정제 및 전처리
- 중요한 이유
    - 현실 데이터는 빈칸, 중복, 잘못된 형식 많다!
    - 지저분한 데이터를 그대로 분석하면 안됨...
    - 정제하는 것이 가장 핵심

In [35]:
import pandas as pd

In [36]:
# 
df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

#### 1. 결측치 - 데이터가 없는 경우
- isna().sum()
- isna() : 각 칸이 비었는지 알려줌
- sum() : 데이터프레임에서 열별 전체 합 뽑음 => True : 1, False : 0

In [37]:
df.isna()   # 오로지 NaN만 뽑고, "결석"은 뽑을 수 없음.

      이름      반     성별     국어     영어     수학
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False   True  False  False
3  False  False  False  False   True  False
4  False  False  False  False  False  False
5  False  False  False  False  False  False

In [38]:
df.isna().sum()

이름    0
반     0
성별    0
국어    1
영어    1
수학    0
dtype: int64

#### 2. 결측치 있는 행 버리기
- dropna()
- 빈칸이 하나라도 있는 행을 통째로 버림
- 데이터가 충분히 많을 때 사용하자

In [39]:
df.dropna()

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [40]:
# 하지만 원본이 바뀌진 않음! 
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [41]:
df = df.dropna() # 수정하며 최신본으로 유지
df_copy = df.copy() # 적절하게 전처리 된 중간 데이터프레임을 원본으로 보관하기
df_copy

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

#### 3. 결측치 채우기
- fillna() : 결측치 채움
- 주로 평균이나 0으로 채움

In [42]:
# 결측치 평균으로 채워보기!
df = pd.read_csv("../data/3-1_students.csv")

korean_score = df["국어"].mean()
df["국어"] = df["국어"].fillna(korean_score) # 앞에 할당하지 않으면 df에 변화 없음

df["영어"] = df["영어"].fillna(df["영어"].mean()) 

df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남  83.6  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

#### 4. 중복 데이터 처리
- duplicated() : 이전과 중복된 행인지 여부를 행별로 True/False로 나타냄

In [43]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

#### 5. 중복 제거
- drop_duplicates()

In [44]:
df = df.drop_duplicates()
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남  83.6  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석

#### 6. 타입을 고치기
- 숫자여야 할 부분에서 아닌 값들을 NaN으로 바꾸기
- pd.to_numeric()

In [45]:
pd.to_numeric(df["수학"], errors="coerce")  # 숫자여야 하는데 아닐 경우 NaN으로 바꿈

0    100.0
1     78.0
2     88.0
3     65.0
4      NaN
Name: 수학, dtype: float64

In [46]:
df["수학"] = pd.to_numeric(df["수학"], errors="coerce")
df

    이름  반 성별    국어    영어     수학
0  김민준  A  남  90.0  80.0  100.0
1  이서연  B  여  85.0  92.0   78.0
2  박도윤  A  남  83.6  75.0   88.0
3  최지우  B  여  70.0  86.8   65.0
4  정하준  A  남  88.0  95.0    NaN

In [47]:
# 마무리: 평균으로 채우기
df["수학"] = df["수학"].fillna(df["수학"].mean())
df

    이름  반 성별    국어    영어      수학
0  김민준  A  남  90.0  80.0  100.00
1  이서연  B  여  85.0  92.0   78.00
2  박도윤  A  남  83.6  75.0   88.00
3  최지우  B  여  70.0  86.8   65.00
4  정하준  A  남  88.0  95.0   82.75

#### 7. 이상치 확인하기
- 비어있거나 타입 다르지 않은데, 값이 이상한 경우
- 몇 점 이상 오류인 경우, - 부호 붙은 경우 등

In [48]:
# 예) 수학 90점 초과는 오류일 경우
df[df["수학"] > 90]

    이름  반 성별    국어    영어     수학
0  김민준  A  남  90.0  80.0  100.0

In [49]:
# 이상 데이터 갯수 확인하기

len(df[df["수학"] > 90])

1