### 도시공원정보표준데이터

#### 도시 공원 데이터
- 우리 도시에 공원이 충분할까?
- 지역마다 어떤 차이가 있을/까?
- 시민의 삶의 질, 복지 등과 연관됨

- **새롭게 알게 된 사실 -> 인사이트**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/3-4_city_park.csv")
df.head()

,관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0,26200-00001,태종대유원지,기타,부산광역시 영도구 전망로 24,부산광역시 영도구 동삼동 산 19-2,35.059695,129.079806,1713763.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
1,26110-00001,용두산공원,근린공원,부산광역시 중구 용두산길 37-55,부산광역시 중구 광복동 2가 1-2,35.100209,129.032278,70812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
2,29200-00028,월전공원,근린공원,NaN,광주광역시 광산구 장록동 751-1,35.132211,126.768588,40038.5,NaN,NaN,NaN,NaN,NaN,1991-06-25,광주광역시 광산구,062-960-6839,2026-06-29
3,29140-00054,극락어린이공원,어린이공원,NaN,광주광역시 서구 유촌동 857,35.165298,126.858437,1643.3,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29
4,29140-00053,서광어린이공원,어린이공원,NaN,광주광역시 서구 쌍촌동 1358,35.157193,126.864497,3067.2,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18499 entries, 0 to 18498
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   관리번호          18499 non-null  str
 1   공원명           18499 non-null  str
 2   공원구분          18499 non-null  str
 3   소재지도로명주소      3131 non-null   str
 4   소재지지번주소       18310 non-null  str
 5   위도            18499 non-null  float64
 6   경도            18499 non-null  float64
 7   공원면적          18499 non-null  float64
 8   공원보유시설(운동시설)  5370 non-null   str
 9   공원보유시설(유희시설)  6252 non-null   str
 10  공원보유시설(편익시설)  5110 non-null   str
 11  공원보유시설(교양시설)  548 non-null    str
 12  공원보유시설(기타시설)  2747 non-null   str
 13  지정고시일         15230 non-null  str
 14  관리기관명         17507 non-null  str
 15  전화번호          17526 non-null  str
 16  데이터기준일자       18499 non-null  str
dtypes: float64(3), str(14)
memory usage: 2.4 MB

#### 데이터 그대로 쓰지 않고 조건을 정해서 처리하기
- 공원 면적을 통계확인

In [ ]:
df.describe()   # 수치형 데이터만

                 위도            경도          공원면적
count  18499.000000  18499.000000  1.849900e+04
mean      36.502789    127.469601  3.033110e+04
std        1.029747      0.847369  2.133286e+05
min       33.218571    125.433012  0.000000e+00
25%       35.558629    126.864257  1.503000e+03
50%       36.785392    127.104036  2.281800e+03
75%       37.433572    128.082836  1.025750e+04
max       38.491242    137.202661  1.486486e+07

In [ ]:
df["공원면적"].mean()

np.float64(30331.098937942592)

In [ ]:
# 공원 면적 중 평균이나 중앙값 등 다양한 대표 지표 설정할 수 있는데, 일단은 크냐 작냐로 나누자
# 데이터 몇개만 뽑기
columns = ["공원명", "공원구분", "공원면적"]

clean_df = df[columns]
clean_df

           공원명   공원구분       공원면적
0       태종대유원지     기타  1713763.0
1        용두산공원   근린공원    70812.0
2         월전공원   근린공원    40038.5
3      극락어린이공원  어린이공원     1643.3
4      서광어린이공원  어린이공원     3067.2
...        ...    ...        ...
18494       율곡  어린이공원     4216.0
18495       천변   수변공원   108420.0
18496      계림8   문화공원     5999.0
18497       학동   역사공원     2049.3
18498      내남3    소공원     1624.0

[18499 rows x 3 columns]

In [ ]:
# 칼럼 하나 새로 생성!
clean_df['큰공원여부'] = clean_df["공원면적"] >= 50000
clean_df

           공원명   공원구분       공원면적  큰공원여부
0       태종대유원지     기타  1713763.0   True
1        용두산공원   근린공원    70812.0   True
2         월전공원   근린공원    40038.5  False
3      극락어린이공원  어린이공원     1643.3  False
4      서광어린이공원  어린이공원     3067.2  False
...        ...    ...        ...    ...
18494       율곡  어린이공원     4216.0  False
18495       천변   수변공원   108420.0   True
18496      계림8   문화공원     5999.0  False
18497       학동   역사공원     2049.3  False
18498      내남3    소공원     1624.0  False

[18499 rows x 4 columns]

#### 2. 면적 순으로 정렬하기
- 큰 값부터 정렬 : sort_values(, ascending = False)
- 작은 값부터 정렬 : sort_values()

In [ ]:
# clean_df.sort_values("공원면적") # 이렇게 하면 작은 값부터 나온다!
clean_df.sort_values("공원면적", ascending=False) # 이렇게 하면 큰 값부터 나온다!

                  공원명  공원구분        공원면적  큰공원여부
4697   랜드마크시티 1호 체육공원  체육공원  14864860.0   True
6304            옥녀봉공원  근린공원   9320660.0   True
14936         불광산근린공원  근린공원   7404000.0   True
2745         수락산<시공원>    기타   6691885.3   True
8868          모악산도립공원  근린공원   5608490.0   True
...               ...   ...         ...    ...
3626    1호 소공원(진위3지구)   소공원         0.0  False
3628     1호 소공원(장당지구)   소공원         0.0  False
18067           대구대공원  근린공원         0.0  False
3429          율리 근린공원  근린공원         0.0  False
3772          봉남 근린공원  근린공원         0.0  False

[18499 rows x 4 columns]

#### 3. 특정 그룹별로 집계 - (통계 계산)
- groupby
- 공원 종류별로 묶어서, 갯수와 합계, 평균 구할 수 있음

In [ ]:
# 공원 면적이 0이거나 얼마 이하인 값들은 제거해야 할 수 있음 (아직 처리 X)

clean_df.groupby("공원구분")["공원면적"].count()    # 같은 공원구분으로 묶고, 공원 면적

공원구분
가로공원         3
근린공원      4112
기타         539
기타공원        29
도시농업공원       7
마을마당         1
묘지공원        39
문화공원       483
소공원       3105
수변공원       405
어린이공원     9301
역사공원       204
주제공원         2
체육공원       269
Name: 공원면적, dtype: int64

In [ ]:
# agg 함수는 원하는 것들만 뽑을 수 있다
summary = clean_df.groupby("공원구분")["공원면적"].agg(["count", "sum", "mean", "median"])
summary

        count           sum           mean     median
공원구분
가로공원        3  1.197100e+04    3990.333333    3272.00
근린공원     4112  3.898640e+08   94811.291314   24909.50
기타        539  2.889889e+07   53615.742356    1117.00
기타공원       29  2.142740e+04     738.875862     335.90
도시농업공원      7  3.158591e+06  451227.271429   49805.90
마을마당        1  5.849000e+02     584.900000     584.90
묘지공원       39  1.821648e+07  467089.287179  214640.40
문화공원      483  2.225936e+07   46085.635197    7721.00
소공원      3105  8.511675e+06    2741.280167    1137.00
수변공원      405  1.307368e+07   32280.692346   11688.20
어린이공원    9301  3.000545e+07    3226.045285    1785.00
역사공원      204  1.199243e+07   58786.443235   15933.00
주제공원        2  6.257890e+04   31289.450000   31289.45
체육공원      269  3.501785e+07  130177.881784   25562.00

In [ ]:
summary.sort_values("count", ascending=False)

        count           sum           mean     median
공원구분
어린이공원    9301  3.000545e+07    3226.045285    1785.00
근린공원     4112  3.898640e+08   94811.291314   24909.50
소공원      3105  8.511675e+06    2741.280167    1137.00
기타        539  2.889889e+07   53615.742356    1117.00
문화공원      483  2.225936e+07   46085.635197    7721.00
수변공원      405  1.307368e+07   32280.692346   11688.20
체육공원      269  3.501785e+07  130177.881784   25562.00
역사공원      204  1.199243e+07   58786.443235   15933.00
묘지공원       39  1.821648e+07  467089.287179  214640.40
기타공원       29  2.142740e+04     738.875862     335.90
도시농업공원      7  3.158591e+06  451227.271429   49805.90
가로공원        3  1.197100e+04    3990.333333    3272.00
주제공원        2  6.257890e+04   31289.450000   31289.45
마을마당        1  5.849000e+02     584.900000     584.90

#### 인사이트
- 어린이공원, 소공원은 갯수 많지만 크기가 작다
- 근린공원은 평균 면적과 전체 공원면적 매우 크다
- 개수 1위는 어린이공원이지만, 전체 면적으로 보면 근린공원이 주된 공원이라 볼 수 있다

#### 4. 교차표 만들기 - pivot_table
- 어떤 두 칼럼(범주)를 가로, 세로로 교차시켜서 요약하는 것
- 관리기관 x 공원구분의 평균 면적을 같이 보려고 할 때

In [ ]:
table_df = clean_df.pivot_table(index="공원구분", 
                                columns="큰공원여부",
                                values="공원명",
                                aggfunc="count",
                                fill_value=0
                                )

table_df
# 결과물: 인덱스는 공원 구분, 행은 큰 공원 여부 O/X만, 안에 들어갈 내용은 공원명의 갯수(count)

큰공원여부   False  True
공원구분
가로공원        3      0
근린공원     2869   1243
기타        512     27
기타공원       29      0
도시농업공원      4      3
마을마당        1      0
묘지공원        5     34
문화공원      387     96
소공원      3094     11
수변공원      332     73
어린이공원    9286     15
역사공원      158     46
주제공원        1      1
체육공원      190     79

#### 5. pivot_table <-> melt
- melt는 그 반대 역할

In [ ]:
# reset_index는 
melt_df = table_df.reset_index().melt(id_vars="공원구분",
                                      var_name="큰공원여부",
                                      value_name="공원수")
melt_df

      공원구분  큰공원여부   공원수
0     가로공원  False     3
1     근린공원  False  2869
2       기타  False   512
3     기타공원  False    29
4   도시농업공원  False     4
5     마을마당  False     1
6     묘지공원  False     5
7     문화공원  False   387
8      소공원  False  3094
9     수변공원  False   332
10   어린이공원  False  9286
11    역사공원  False   158
12    주제공원  False     1
13    체육공원  False   190
14    가로공원   True     0
15    근린공원   True  1243
16      기타   True    27
17    기타공원   True     0
18  도시농업공원   True     3
19    마을마당   True     0
20    묘지공원   True    34
21    문화공원   True    96
22     소공원   True    11
23    수변공원   True    73
24   어린이공원   True    15
25    역사공원   True    46
26    주제공원   True     1
27    체육공원   True    79

#### 6. 값을 하나씩 바꾸기

In [ ]:
df.columns

Index(['관리번호', '공원명', '공원구분', '소재지도로명주소', '소재지지번주소', '위도', '경도', '공원면적',
       '공원보유시설(운동시설)', '공원보유시설(유희시설)', '공원보유시설(편익시설)', '공원보유시설(교양시설)',
       '공원보유시설(기타시설)', '지정고시일', '관리기관명', '전화번호', '데이터기준일자'],
      dtype='str')

In [ ]:
clean_df.head()

       공원명   공원구분       공원면적  큰공원여부
0   태종대유원지     기타  1713763.0   True
1    용두산공원   근린공원    70812.0   True
2     월전공원   근린공원    40038.5  False
3  극락어린이공원  어린이공원     1643.3  False
4  서광어린이공원  어린이공원     3067.2  False

In [ ]:
# lambda와 apply 이용해서 더 쉽게 정리할 수 있음
clean_df['규모'] = clean_df['공원면적'].apply(lambda x : "큰공원" if x > 30000 else "작은공원")
clean_df

           공원명   공원구분       공원면적  큰공원여부    규모
0       태종대유원지     기타  1713763.0   True   큰공원
1        용두산공원   근린공원    70812.0   True   큰공원
2         월전공원   근린공원    40038.5  False   큰공원
3      극락어린이공원  어린이공원     1643.3  False  작은공원
4      서광어린이공원  어린이공원     3067.2  False  작은공원
...        ...    ...        ...    ...   ...
18494       율곡  어린이공원     4216.0  False  작은공원
18495       천변   수변공원   108420.0   True   큰공원
18496      계림8   문화공원     5999.0  False  작은공원
18497       학동   역사공원     2049.3  False  작은공원
18498      내남3    소공원     1624.0  False  작은공원

[18499 rows x 5 columns]

In [ ]:
# 세분화해본다면
# 3만 이하는 작은공원, 3만~5만은 중간공원, 5만 이상은 큰공원
# 이럴 땐 elif가 아니라 else 안에 또 if 넣어야 한다

clean_df['규모'] = clean_df['공원면적'].apply(lambda x : "큰공원" if x >= 50000 else ("중간공원" if x >= 30000 else "작은공원"))
clean_df

           공원명   공원구분       공원면적  큰공원여부    규모
0       태종대유원지     기타  1713763.0   True   큰공원
1        용두산공원   근린공원    70812.0   True   큰공원
2         월전공원   근린공원    40038.5  False  중간공원
3      극락어린이공원  어린이공원     1643.3  False  작은공원
4      서광어린이공원  어린이공원     3067.2  False  작은공원
...        ...    ...        ...    ...   ...
18494       율곡  어린이공원     4216.0  False  작은공원
18495       천변   수변공원   108420.0   True   큰공원
18496      계림8   문화공원     5999.0  False  작은공원
18497       학동   역사공원     2049.3  False  작은공원
18498      내남3    소공원     1624.0  False  작은공원

[18499 rows x 5 columns]

In [ ]:
# 사실 def로 해서 apply하는 게 제일 편하다!

def clean_func(x):
    if x >= 50000:
        return "큰공원"
    elif x >= 30000:
        return "중간공원"
    else:
        return "작은공원"

clean_df['규모함수'] = clean_df['공원면적'].apply(clean_func)
clean_df

In [ ]:
# cut 기능으로 할 수도 있지만... 잘 안씀
clean_df['규모cut'] = pd.cut(clean_df['공원면적'], 
                           bins = [0,30000,50000,float('inf')],   # 구간 나누기
                           labels=["작은공원", "중간공원", "큰공원"],
                           right=False)

clean_df

           공원명   공원구분       공원면적  큰공원여부    규모 규모cut
0       태종대유원지     기타  1713763.0   True   큰공원   큰공원
1        용두산공원   근린공원    70812.0   True   큰공원   큰공원
2         월전공원   근린공원    40038.5  False  중간공원  중간공원
3      극락어린이공원  어린이공원     1643.3  False  작은공원  작은공원
4      서광어린이공원  어린이공원     3067.2  False  작은공원  작은공원
...        ...    ...        ...    ...   ...   ...
18494       율곡  어린이공원     4216.0  False  작은공원  작은공원
18495       천변   수변공원   108420.0   True   큰공원   큰공원
18496      계림8   문화공원     5999.0  False  작은공원  작은공원
18497       학동   역사공원     2049.3  False  작은공원  작은공원
18498      내남3    소공원     1624.0  False  작은공원  작은공원

[18499 rows x 6 columns]