### 데이터 병합
- 모든 필요한 데이터가 하나의 파일에 닜는 것은 아님
- 예) 우리 도시 공원 데이터
    - 도시에 공원이 충분히 많을까? -> 1. 도시 면적, 2. 도시 인구수 데이터 필요
    - 지역마다 격차가 없을까? > 1. 도시 면적, 2. 도시 인구수 데이터 필요
    - 공원 데이터로만 보면 면적 넓은 도시가 좋을 것 같지만 인구 너무 많으면 살기 좋다고 말하기 힘듦
- 시민 1명당 공원 면적을 계산해야 진짜 비교가 가능!

### 1. 데이터 합치기 - 세로로 합치기 : concat

In [1]:
import pandas as pd

daejeon_park = pd.DataFrame({
    "지역": ["대전", "대전", "대전"],
    "공원명": ["한밭수목원", "샘머리공원", "올림픽체육공원"],
    "공원구분": ["도시자연공원", "근린공원", "체육공원"],
    "공원면적": [387000, 12500, 45000],
})

sejong_park = pd.DataFrame({
    "지역": ["세종", "세종", "세종"],
    "공원명": ["세종호수공원", "방축천공원", "밀마루전망공원"],
    "공원구분": ["도시자연공원", "근린공원", "근린공원"],
    "공원면적": [705000, 32000, 8900],
})

In [2]:
sejong_park

   지역      공원명    공원구분    공원면적
0  세종   세종호수공원  도시자연공원  705000
1  세종    방축천공원    근린공원   32000
2  세종  밀마루전망공원    근린공원    8900

In [ ]:
total_df = pd.concat([daejeon_park, sejong_park], ignore_index=True) # 만약 False하면 인덱스가 012012가 된다.!
total_df

   지역      공원명    공원구분    공원면적
0  대전    한밭수목원  도시자연공원  387000
1  대전    샘머리공원    근린공원   12500
2  대전  올림픽체육공원    체육공원   45000
3  세종   세종호수공원  도시자연공원  705000
4  세종    방축천공원    근린공원   32000
5  세종  밀마루전망공원    근린공원    8900

#### 2. 가로로 합치기 - merge

In [4]:
data1 = pd.DataFrame({
    "지역" : ["대전", "세종"],
    "인구수" : [1_450_000, 380_000],
})
data1

   지역      인구수
0  대전  1450000
1  세종   380000

In [ ]:
merged_df = pd.merge(total_df, data1, on="지역")    #on 없어도 지역으로 합쳐지긴 함
merged_df

   지역      공원명    공원구분    공원면적      인구수
0  대전    한밭수목원  도시자연공원  387000  1450000
1  대전    샘머리공원    근린공원   12500  1450000
2  대전  올림픽체육공원    체육공원   45000  1450000
3  세종   세종호수공원  도시자연공원  705000   380000
4  세종    방축천공원    근린공원   32000   380000
5  세종  밀마루전망공원    근린공원    8900   380000