### 벡터 DB
- 문서가 많을 때 대량 검색을 알아서 해주는 벡터 DB 구축
- 인덱싱(색인), 100만개 정도 되더라도 검색하고 계산이 거의 바로 된다
- 메타데이터(카테고리, 날짜 등)를 바탕으로 검색이 가능

Question(질문) -> Retriever(검색기) -> 벡터DB -> Generate(응답 생성)

- 근사 검색(ANN)
- HNSW
    - 벡터들을 여러 층의 그래프로 연결해두고, 위에서 방향 잡아서 아래로 내려가며 데이터 훑는 방식

#### 벡터  DB 종류
- chromaDB
- FAISS(옛날 로컬 벡터 DB)
- Qdrant
- Pinecone(유료)
- pgvector - 기존의 postgreSQL에 플러그인만 추가하면 사용 가능
- Neo4j(GraphDB 용인데 벡터 DB에도 쓰임)
- milvus - 데이터 엄청 많을 때

In [46]:
import chromadb

print(chromadb.__version__)

1.5.9

In [47]:
import pandas as pd

df = pd.read_csv("../data/11-1_뉴스정제.csv").head(200).reset_index(drop=True)
df.head(3)

,제목,본문,카테고리,요약,출처URL,정제본문
0,현대백화점그룹 더현대 광주 추진,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,경제,"6 6일 현대백화점그룹이 광주시에 문화복합몰을 만든다고 6일 밝혔으며, 광주시는 서...",https://n.news.naver.com/mnews/article/001/001...,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...
1,이스타항공 이상직 회사와 무관…오해 살 언동 말아야,전주 뉴시스 김얼 기자 이스타항공 자금 배임·횡령으로 전주교도소에 수감됐었던 이상직...,경제,이이스항공은 자금 배임·횡령으로 전주교도소에 수감됐었던 이상직 전 의원이 출소한 것...,https://n.news.naver.com/mnews/article/003/001...,전주 뉴시스 김얼 기자 이스타항공 자금 배임 횡령으로 전주교도소에 수감됐었던 이상직...
2,농협은행 농협금융 출범 10주년 기념주화 NFT 이벤트,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 ‘10주년 기념주...,경제,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 소셜미디어 인스타...,https://n.news.naver.com/mnews/article/366/000...,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 10주년 기념주화...

In [48]:
docs = df['정제본문'].tolist()

print(len(docs))

200

In [49]:
# 메타데이터로 쓸만한 것 확인 - 나중엔 필요 메타데이터는 LLM으로 처리
df[['제목', '카테고리', '출처URL']].head(3)

,제목,카테고리,출처URL
0,현대백화점그룹 더현대 광주 추진,경제,https://n.news.naver.com/mnews/article/001/001...
1,이스타항공 이상직 회사와 무관…오해 살 언동 말아야,경제,https://n.news.naver.com/mnews/article/003/001...
2,농협은행 농협금융 출범 10주년 기념주화 NFT 이벤트,경제,https://n.news.naver.com/mnews/article/366/000...

### ChromaDB 컬렉션 만들기
컬렉션 : 문서를 담는 단위 -> 이름 적어주면 됨
1. 임베딩 함수가 뭔지
2. 거리 척도가 뭔지 (우리는 코사인 유사도)

In [50]:
import os
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction  # chromaDB 자체에서 Openai 임베딩 모델 있음
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
client = OpenAI()

In [51]:
embeddings = OpenAIEmbeddingFunction(
    model_name="text-embedding-3-small"
)

embed_client = chromadb.Client()

# collection은 
collection = embed_client.get_or_create_collection(
    name="news_collection",
    embedding_function=embeddings,
    configuration={'hnsw' : {"space" : "cosine"}}

)

In [52]:
collection

Collection(name=news_collection)

In [53]:
ids = df.index.astype(str).tolist()
metadata = df[['제목', '카테고리', '출처URL']].to_dict('records')
metadata

[{'제목': '현대백화점그룹 더현대 광주 추진',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013293519?sid=101'},
 {'제목': '이스타항공 이상직 회사와 무관…오해 살 언동 말아야',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011282043?sid=101'},
 {'제목': '농협은행 농협금융 출범 10주년 기념주화 NFT 이벤트',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/366/0000824966?sid=101'},
 {'제목': '오늘부터 유류세 인하 폭 확대…하반기 바뀌는 세제·금융 정책은',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/437/0000304023?sid=101'},
 {'제목': '푸르덴셜생명 더 큰 드림 변액연금보험Ⅱ에 신규펀드 13종 추가',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/014/0004860779?sid=101'},
 {'제목': '오늘부터 사고 나면 중대재해처벌법 기소 가능성 더 커져',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/277/0005111594?sid=101'},
 {'제목': '역세권에 신규분양 봇물…천안 부성지구 한라비발디 654가구 분양',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/374/0000293010?sid=101'},
 {'제목': '식량 대란 오나',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/015/0004720058?sid=101'},
 {'제목': 'G마켓·옥션 여름 휴가 겨냥…여행 빅세일 진행',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006190764?sid=101'},
 {'제목': 'KT 리벨리온과 손잡고 국내 AI반도체 생태계 설계',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/014/0004863320?sid=101'},
 {'제목': '삼바 MSD와 2768억 위탁생산계약 체결',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/296/0000057378?sid=101'},
 {'제목': '秋 “하반기 수출여건도 녹록지 않아… 근로시간제 개선 등 인력난 완화”',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/021/0002520259?sid=101'},
 {'제목': '2022 국제안전보건전시회 개막',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013287320?sid=101'},
 {'제목': '레미콘운송노조 파업 3일째 레미콘제조사와 재협상',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013285171?sid=101'},
 {'제목': '기업 세금부담 줄인다… 낙수효과 이번엔 통할까',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/417/0000828541?sid=101'},
 {'제목': '조주현 중기부 차관 원전 中企 지원에 모든 역량 결집할 것',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/008/0004766988?sid=101'},
 {'제목': '디자인 설명하는 문일한 연구원',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011285917?sid=101'},
 {'제목': '팔라 NFT 마켓·토큰 클립 지갑 지원',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/092/0002261711?sid=105'},
 {'제목': '동·서학개미의 눈물…올해 삼성전자 28%·테슬라 35% ↓',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/277/0005112108?sid=101'},
 {'제목': '다가온 실적시즌…하락장 이길 서프라이즈 종목은',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005256465?sid=101'},
 {'제목': 'NH농협카드 7월 맞이 여름휴가 이벤트',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/014/0004861555?sid=101'},
 {'제목': '환경부 탄소중립 특성화대학원 2곳 선정...고급인재 양성',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/016/0002012371?sid=101'},
 {'제목': 'SSG닷컴 강남으로 본사 이전 완료',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/030/0003028045?sid=101'},
 {'제목': '쿠쿠 창문형에어컨 오늘 설치 서비스 실시',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/092/0002261756?sid=105'},
 {'제목': '노브랜드버거 데이 이벤트 참가하는 관중들',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011287157?sid=101'},
 {'제목': '환경부 유출지하수 다용도 복합 활용 모델 발표',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006198013?sid=101'},
 {'제목': '불붙은 한남2구역 수주전 1군건설사 대거 몰려 ‘점입가경’',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/243/0000028272?sid=101'},
 {'제목': 'SK ES 미디어룸 열고 소통…유정준 천연가스로 탄소중립 보완',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/011/0004072174?sid=101'},
 {'제목': '김범석 쿠팡 의장 작년 연봉 18억…전년비 10분의 1 급감 왜',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005256366?sid=101'},
 {'제목': '조간브리핑 지방 아파트 역전세 현상 속출…다주택자 규제 완화에 사려는 사람 없어',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/374/0000292912?sid=101'},
 {'제목': '유류세 추가 인하 북새통 이룬 주유소 포토',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/629/0000158440?sid=101'},
 {'제목': '침체 우려 지속 유럽증시 일제 하락 출발…獨 1.17%↓',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006192448?sid=101'},
 {'제목': '3년만에 만난 한일 재계 새 미래 열자',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/009/0004986731?sid=101'},
 {'제목': '신세계百 식품관 리뉴얼 통했다..1년만에 매출 2배',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005258726?sid=101'},
 {'제목': '한탄강 포천시 영평교 지점 홍수경보 해제',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/056/0011294065?sid=105'},
 {'제목': '무등의 아침 해파리떼에 기름값까지…엎친 데 덮친 어민들',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/056/0011294367?sid=101'},
 {'제목': '얼음보고 무더위 잊으세요',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013287511?sid=101'},
 {'제목': '경제부총리 주재 금융당국 조찬간담회',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013286106?sid=101'},
 {'제목': '한전·효성중공업  전력설비 예방진단·자산관리분야 민·관 협력',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006191055?sid=101'},
 {'제목': 'LGU·LG전자·LG생건 그룹 창립 75주년 기념 이벤트',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/277/0005113009?sid=105'},
 {'제목': '비상경제장관회의 주재하는 추경호 부총리',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013285460?sid=101'},
 {'제목': 'LG전자 2030년까지 추진할 ESG 전략과제 선정',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/382/0000990109?sid=101'},
 {'제목': '행복지수 100%...시골은 버킷리스트 무대',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/052/0001758969?sid=101'},
 {'제목': 'HJ중공업 구미 동락공원서 아름다운 구미 만들기 플로깅',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006194418?sid=101'},
 {'제목': '유류세 추가 인하 첫날…정부 현장 점검',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/014/0004860751?sid=101'},
 {'제목': '글로벌 공급망 차질 지속 땐 車·배터리 생산 쇼크',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/081/0003284678?sid=101'},
 {'제목': '슈나이더 일렉트릭 스마트팩토리 솔루션으로 생산 효율↑',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/030/0003029209?sid=105'},
 {'제목': '골프장 요금 인상·예약 독점에 제동',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/087/0000911313?sid=101'},
 {'제목': 'LG전자·SM 홈트 시장 정조준… 애플 피트니스 뛰어넘을 것',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/417/0000828005?sid=101'},
 {'제목': '2분기에만 20% 넘게 하락한 코스닥…유일 상승 업종은',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011279505?sid=101'},
 {'제목': '원희룡 공공기관 자체 혁신안 문제 의식 없다 질타',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/469/0000684537?sid=101'},
 {'제목': '은행 가계대출 반년간 9조 넘게 줄었다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011280545?sid=101'},
 {'제목': '국제로타리 3640지구 총재에 구교운 대방건설 회장',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/052/0001758832?sid=101'},
 {'제목': '6월 더위에 전력수요 역대 동월 최고‥최대전력 7만MW 첫 돌파',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/214/0001206683?sid=101'},
 {'제목': '부산 엑스포 유치 힘내요…삼성전자 부산 전역매장서 응원',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005258312?sid=101'},
 {'제목': '웰스 7월 여름맞이 할인 프로모션…정수기 렌털료 할인',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011282805?sid=101'},
 {'제목': '규제지역 해제 대구 부동산 시장 먹구름 걷힐까',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/243/0000028372?sid=101'},
 {'제목': '공영홈쇼핑 ‘여성기업주간’ 맞아 특별 생방송',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/138/0002127744?sid=105'},
 {'제목': 'LGU 실시간 건강관리 서비스 ‘스마트 실버케어’ 실증',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/138/0002127795?sid=105'},
 {'제목': '가스公 LNG 벙커링 사업으로 저탄소 친환경 에너지 시대 선도',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/030/0003027952?sid=101'},
 {'제목': '금감원 스트레스 테스트 돌입… 은행권 자발적 배당 축소 나서나',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/366/0000825189?sid=101'},
 {'제목': '롯데제과·롯데푸드 합병…3.7조 원 식품 기업 탄생 시너지 기대',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/629/0000158520?sid=101'},
 {'제목': '증권사 ‘빚투’ 계좌 10개 중 3개가 ‘고위험’',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/032/0003157818?sid=101'},
 {'제목': '배스킨라빈스  ‘캠핑용 트라이팟 선풍기’  사전예약',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/123/0002279734?sid=101'},
 {'제목': '윤석열 정부서 눈 밖에 난 에너지 공기업…코레일도 눈총',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013286014?sid=101'},
 {'제목': '코스피 1년 8개월 만에 2300선 아래로...원·환율 급등',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006201585?sid=101'},
 {'제목': '중기부 규제개선 간담회 개최···조 차관 덩어리 규제 개선',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/092/0002261783?sid=105'},
 {'제목': '평택 지식산업센터 오션센트럴비즈 이달 공급 앞둬',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/215/0001041117?sid=101'},
 {'제목': '넷마블 샹그릴라 프론티어 게임 만든다…애니 제작위도 참여',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013297461?sid=105'},
 {'제목': '6월 소비자물가 외환위기 이후 최고치',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006198461?sid=101'},
 {'제목': '상반기 서울 아파트값 3년 만에 하락…강남4구·용산은 빼고',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/028/0002597438?sid=101'},
 {'제목': '콘티넨탈코리아 마틴 큐퍼스 신임 대표이사 선임',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011283310?sid=101'},
 {'제목': '다올금융그룹 제4회 ‘DAOL Venture Challenge 2022’ 개최',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/016/0002011018?sid=101'},
 {'제목': '캠코 금융취약계층 상해보험 무료가입 지원',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/014/0004860753?sid=101'},
 {'제목': '기고 초우량 서비스 경영의 세 가지 조건',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/009/0004985406?sid=101'},
 {'제목': '삼성 네오 QLED 8K 디지털아트 전시회',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/029/0002742115?sid=101'},
 {'제목': '다음 블로그 17년 만에 서비스 종료…티스토리와 통합',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/031/0000683351?sid=105'},
 {'제목': '전기차에 적용되는 나노기술',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006201381?sid=101'},
 {'제목': '외국인 유치 사활.. 동남아 관광객 제주 오세요',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/661/0000009258?sid=101'},
 {'제목': '신용거래융자 4거래일 만에 감소…17조9390억원',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005260364?sid=101'},
 {'제목': 'CP매입 등 사실상 코로나 기업지원 축소',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/011/0004072488?sid=101'},
 {'제목': '78월 대조기 “해안가 저지대 침수 대비해야”',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/119/0002618257?sid=101'},
 {'제목': '바디프랜드 안마의자 넘어 홈 헬스케어 기업 꿈꾼다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/119/0002618724?sid=101'},
 {'제목': '은행 이자장사 경고에…예금 금리 높이고 대출 금리 낮춰',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/277/0005112001?sid=101'},
 {'제목': '앞으로 공유수면 점용·사용시 이해 관계자 의견 듣는다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011285033?sid=101'},
 {'제목': '재택플러스 멍푸치노·펫프터눈티…아시나요',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/214/0001206272?sid=101'},
 {'제목': '파트라 신제품 사무용 의자 라보 시리즈 양산 1호 출고 기념식',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006196610?sid=101'},
 {'제목': 'IBS 중이온가속기연구소 초대 소장에 홍승우 성균관대 교수',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013283701?sid=105'},
 {'제목': '삼성 스마트기기 부품 배송 포장재 친환경 소재 적용 ↑',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/277/0005113761?sid=105'},
 {'제목': '대중관세 철폐시 美 인플레 0.3%p 효과에 그칠 것',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006198698?sid=101'},
 {'제목': '삼성전자 지난해 세금 14.8조 납부…80%는 한국에 냈다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011279196?sid=101'},
 {'제목': '비상경제차관회의 발언하는 방기선 차관',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011279175?sid=101'},
 {'제목': '쉬는 일요일에도 새벽배송 가능…대형마트 규제 완화 기대감 커져',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/024/0000075932?sid=101'},
 {'제목': '대구로 본사 옮긴다는 티웨이항공… ‘에어부산’ 잃을 처지 부산은 어쩌나',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/082/0001163552?sid=101'},
 {'제목': '수입 곡물가 3분기에 더 오른다…밥상물가 고공행진 불가피',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/016/0002010617?sid=101'},
 {'제목': '뉴스까페 제약바이오 수십 곳 노조 있는데...국내 회사가 안 보인다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/374/0000293410?sid=101'},
 {'제목': 'LG전자 전장사업 질주… 상반기에만 8조원 수주',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/023/0003701879?sid=105'},
 {'제목': '폭스바겐 2030년까지 유럽 배터리 공장 5곳 건설…26조원 투자',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/138/0002128249?sid=105'},
 {'제목': '대웅제약 향남공장 사업장 보건관리 우수사례 최우수상',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/029/0002743084?sid=105'},
 {'제목': '돈 빌리기 힘들어지니 인터넷銀으로 우르르',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/029/0002741975?sid=101'},
 {'제목': '한은 빅스텝하면 실물경제 침체 우려',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/374/0000293151?sid=101'},
 {'제목': '“자산관리의 시작은 고객”… 부동산·세무·투자상담 종합 서비스',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/020/0003437469?sid=101'},
 {'제목': '환영사하는 김용석 항공정책실장',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011283103?sid=101'},
 {'제목': 'KT클라우드 하이브리드 클라우드 서비스 ‘클라우드팜’ 출시',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/366/0000824946?sid=105'},
 {'제목': '성북구 러브버그 대응 선제 방역',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006197702?sid=101'},
 {'제목': '농협중앙회 「상호금융 MBA」34기 수료식 개최',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/022/0003711018?sid=101'},
 {'제목': '산업 디지털전환 촉진법 시행...하반기 산업 디지털 전환 종합계획 수립',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/014/0004861846?sid=101'},
 {'제목': 'KB손보다이렉트 해외 입원일당 강화 여행보험 출시',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011285324?sid=101'},
 {'제목': '특징주 이화전기 배터리 시장 진출 시동 걸자 상한가',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/011/0004072127?sid=101'},
 {'제목': '조선하청지회 대우조선해양 점거 농성',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013293097?sid=101'},
 {'제목': '폭염에 찾는 수박',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013285276?sid=101'},
 {'제목': '월 10만원 저축하면 정부가 10만원 더…18일부터 청년내일저축계좌 모집',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/024/0000075873?sid=101'},
 {'제목': 'SKB 클라우드PC 솔루션 국정원 보안기능확인서 획득',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/029/0002742598?sid=105'},
 {'제목': 'KT 올레 tv 서비스 혁신 위한 미디어 스타트업 협력 나선다',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/076/0003889413?sid=105'},
 {'제목': 'SK텔레콤 SK하이닉스 AI와 반도체 현업 노하우 대학에 제공',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005261869?sid=105'},
 {'제목': '與 물가특위 오늘 주유소 찾아 유류세 인하 체감도 점검',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011278800?sid=101'},
 {'제목': '신한라이프 AI 헬프데스크 ‘아이온’ 오픈',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/138/0002127915?sid=105'},
 {'제목': '현대차그룹 美 신사업 투자 법인 설립… 바이든 방한 투자계획 일환',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/417/0000827996?sid=101'},
 {'제목': '세무조사도 친기업적…김창기 어떤 메시지 내놓을까',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/123/0002279751?sid=101'},
 {'제목': '주요기업 IT투자현황⑩ 네이버카카오 지난해 IT에 얼마나 투자했나',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/138/0002128166?sid=105'},
 {'제목': '문과생도 IT 인재로 육성…취업률 59% ‘눈길’',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/056/0011295703?sid=101'},
 {'제목': '마크 리 어플라이드 코리아 대표 글로벌 투자 서밋 라운드테이블 참석',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006201440?sid=101'},
 {'제목': 'SP500 1H 21% 손실 52년래 최대…최대 위험은 인플레·연준',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006190702?sid=101'},
 {'제목': '“빚투 손실금 탕감이 웬말” 커지는 불공정 논란',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/005/0001537354?sid=101'},
 {'제목': '연일 폭염 전력 수급 현황은',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013287887?sid=101'},
 {'제목': '코렌텍 선헬스케어인터내셔널 지분 43.4% 취득 결정',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005256985?sid=101'},
 {'제목': 'SIEK 갓 오브 워 라그나로크 11월 9일 출시',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/079/0003661739?sid=105'},
 {'제목': '韓 수출 전망 악화에 원·달러 환율 1300원 재돌파',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/366/0000825510?sid=101'},
 {'제목': '경기침체 온다지만…개발자 뽑아요',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005259610?sid=101'},
 {'제목': '상반기 신용도 상향기조였지만…투자와 투기 양극화',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005259581?sid=101'},
 {'제목': '뉴스프라임 처음 집 사면 LTV 80%…하반기 달라지는 정책은',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/422/0000549228?sid=101'},
 {'제목': '역삼 창업가거리 마루360 업무공간 개방…마루패스 출시',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/008/0004766393?sid=101'},
 {'제목': '비상경제장관회의 주재하는 추경호 부총리',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/421/0006194012?sid=101'},
 {'제목': '하나증권 7월부터 새 간판…전 부문 재도약 계기',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/119/0002617303?sid=101'},
 {'제목': '미니스톱 세븐일레븐 수준으로 연봉 인상… “양사 통합 속도 낸다”',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/366/0000825843?sid=101'},
 {'제목': '변호사는 빠져라 막무가내 중대법 수사',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/009/0004986133?sid=101'},
 {'제목': '軍 AI전투체계로 확 바꾼다…GP소대장 등 야간·휴일수당 신설',
  '카테고리': 'IT과학',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013292828?sid=105'},
 {'제목': '허준이 교수 한국계 최초로 수학계 노벨상 필즈상 수상',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/448/0000365286?sid=101'},
 {'제목': 'LH 부천대장 A1블록 대국민 아이디어 공모전 시상식 개최',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/119/0002617296?sid=101'},
 {'제목': '속보레미콘사·운송사업자 운송료 협상 또 결렬',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005258693?sid=101'},
 {'제목': '잔디·흙·선크림 얼룩에 골치…집에서 제거 이렇게알아봅시다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011284998?sid=101'},
 {'제목': '스튜디오드래곤 성장성·수익성 동시에 가져가는 해신한',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/018/0005256435?sid=101'},
 {'제목': '온라인 판매 반려동물 사료 성분·표시 점검',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/001/0013283273?sid=101'},
 {'제목': '오늘부터 전기·가스요금전기차 충전요금 줄인상',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/082/0001162859?sid=101'},
 {'제목': '정부 쌀 10만톤 추가 매입해 시장 격리',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/011/0004071624?sid=101'},
 {'제목': '“이산화탄소를 저장하라”…대규모 저장장소 찾는다',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/031/0000682437?sid=101'},
 {'제목': '새마을금고 ‘MG 휴먼 브릿지 청년 창업캠프’ 개최',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/119/0002617357?sid=101'},
 {'제목': '아피메즈 건국대와 산학협력…바이오 신약 원료물질 개발',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/277/0005113933?sid=101'},
 {'제목': '신한은행 연 5% 초과 주담대 금리 연 5%로 일괄 감면',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/003/0011281847?sid=101'},
 {'제목': '제주도 물가상승률은 이미 ‘금융 위기’… 전년比 7.4%↑',
  '카테고리': '경제',
  '출처URL': 'https://n.news.naver.com/mnews/article/005/0001537784?sid=101'},
 {'제목': '초복 D7…롯데마트 13일까지 닭고기·오리고기 할인',
  '카테고리': '경제',

In [ ]:
# 컬렉션에 추가
collection.upsert(ids=ids, documents=docs, metadatas=metadata)  # id 잘 안넣으면 랜덤으로 하기 때문에 잘 지정해줘야?
collection.count()

200

In [55]:
# 검색기
question = "대출 정보에 대해서 알려줘"

result = collection.query(query_texts=[question], n_results=5)  # 아까 1_RAG에서우리가 구현했던 기능이 한줄로 구현됨
result

{'ids': [['111', '51', '120', '130', '3']],
 'embeddings': None,
 'documents': [['보건복지부 제공 보건복지부는 저소득 청년에 저축액의 최대 3배까지 추가 적립해주는 청년내일저축계좌 가입자를 오는 18일부터 모집한다고 밝혔다 해당 제도는 월 10만원을 저축하면 정부가 지원금 월 10만원을 추가 적립하는 방식으로 3년간 지원해 청년의 자산 형성을 도와주는 청년특별대책제도다 참여자는 3년 만기 시 본인 납입액 360만원을 포함해 총 720만원과 예금이자를 수령하게 된다 청년내일저축계좌는 신청 시점 기준 만 19 34세인 청년이 대상이다 본인 소득 가구 소득 가구 재산 등 3가지 기준을 충족해야 한다 신청 당시에 근로 중이어야 하며 근로 사업소득이 50만원 초과 200만원 이하여야 한다 또한 자신이 속한 가구의 소득이 기준 중위소득 100 2022년 4인 가구 기준 512만1080원 이하여야 한다 가구 재산 기준은 지역에 따라 차등이 있다 대도시 3억5000만원 중소도시 2억원 농어촌 1억7000만원 이하인 가구가 대상이다 신청자가 기초생활수급자이거나 차상위계층 기준 중위소득 50 이하 이라면 혜택이 훨씬 크다 참여자가 10만원을 적립할 때마다 정부 지원금 30만원이 지급된다 3년 뒤 만기 때 총 1440만원의 적립금과 예금이자를 수령하게 된다 또한 가입 가능 연령이 만 15 39세로 더 넓으며 근로 사업소득기준도 면제된다 복지부는 그동안 청년층 대상 자산형성지원 사업을 해왔으나 그 대상이 수급자와 차상위계층에만 한정됐었다 그러나 이번에는 중위소득 100 이하인 청년으로 대상이 확대되면서 신청 대상이 지난해 1만8000명에서 올해 10만4000명으로 6배 증가했다 가입을 희망하는 청년은 복지로 홈페이지 www bokjiro go kr 를 통해 신청하면 된다 정부는 원활한 신청을 위해 신청 시작일인 18일부터 2주 7월 18 29일 간은 출생일 기준으로 5부제를 시행한다 5부제 기간에 신청하지 못한 경우 8월 1 5일에 생일과 무관하게 신청할 수 있다 대상자 선정 결과는 소득 재산 조사 등을 거쳐 10월 중에 발표된다 곽숙영 복지부 복지정책관은 이번 사업이 어려움을 겪고 있는 청년층에게 도움이 되기를 바라며 앞으로도 청년층을 적극 지원하기 위해 노력하겠다 고 말했다',
   '기사내용 요약 가계대출 잔액 699조6521억원 금리상승 자산시장 주춤 영향 하반기 규제 강화에 증가 전환 어려울 듯 서울 뉴시스 이주혜 기자 국내 주요 은행의 가계대출 잔액이 올해 상반기 감소한 것으로 나타났다 6개월간 9조원 이상이 줄었다 특히 신용대출이 8조원 넘게 줄면서 가계대출 감소세를 이끈 것으로 분석됐다 1일 은행권에 따르면 KB국민 신한 하나 우리 NH농협은행의 지난달 말 기준 가계대출 잔액은 699조6521억원으로 전월보다 1조4094억원 감소했다 가계대출 잔액이 700조원대 아래로 떨어진 것은 지난해 8월 이후 약 10개월 만이다 가계대출은 올해 1월부터 6개월 연속 감소세를 지속하면서 반년간 9조4008억원이 줄었다 은행권 관계자는 상반기 대출 감소는 금리 영향이 제일 크다고 볼 수 있다 며 자산시장도 상승세를 멈추면서 대출을 받아서 투자하는 수요가 사라졌다 실수요자가 아니면 대출을 받지 않는 분위기 라고 설명했다 주택담보대출은 지난달 소폭 늘면서 한 달 만에 증가했다 지난달 말 기준 주담대 잔액은 506조7714억원로 전월보다 991억원 늘었다 올해 들어 지난달까지 6개월간 주담대 잔액은 1조3668억원 늘어난 것으로 나타났다 지난해 하반기에는 한 달에만 3조원 이상 4조원까지도 늘어난 것과 비교하면 증가세가 둔화한 것이다 전월에는 감소세를 보이기도 했다 신용대출은 지난해 12월부터 지난달까지 꾸준히 줄면서 가계대출 감소세를 견인했다 올해에만 8조8783억원이 줄었다 지난달 말 신용대출 잔액은 130조6789억원으로 전월보다 1조1204억원이 감소했다 감소폭은 전월 6613억원 보다 커졌다 지난해까지만 해도 낮은 금리와 자산시장의 높은 수익률에 대출을 통한 영끌 로 투자에 나선 이들이 많았지만 금리가 가파르게 오르고 자산시장이 침체하면서 신용대출도 감소세를 지속하고 있다 집단대출은 지난달 말 기준 159조9421억원으로 전월 보다 3412억원 늘었다 4개월 연속 증가세를 지속했다 전세대출은 5개월 연속 늘었다 전월 대비 4479억원 늘어난 132조9061억원으로 집계됐다 전세대출 잔액은 올해 상반기 3조2092억원 증가했다 시중은행 관계자는 전세대출은 실수요자 중심이기 때문에 금리가 올라도 필요한 사람은 대출을 받을 수밖에 없다 면서 전셋값이 오르면 대출도 늘어나게 된다 고 설명했다 금리 상승이 계속되고 대출 관련 규제가 강화되면서 하반기에도 가계대출 감소 분위기는 크게 바뀌기 어려울 전망이다 은행권 관계자는 7월부터 총부채원리금상환비율 DSR 규제가 강화되고 금리도 오르다 보니 대출이 늘어날 이유가 없는 것 같다 면서 실수요자 중심으로는 지금과 같은 분위기를 반전시키기는 어려울 것 이라고 말했다',
   'KBS 부산 앵커 문과를 나와 죄송합니다 라는 자조적 말이 유행할 정도로 문과생의 취업 문턱은 갈수록 높아지는 상황인데요 기업이 직접 가르쳐서 뽑는 식으로 비전공자들도 IT 회사 취업이라는 벽을 허물고 있어 눈길을 끌고 있는데요 강예슬 기자가 보도합니다 리포트 동의대학교 중어중문학과를 졸업한 이현진 씨 지방대생에 비전공자라는 불리한 조건에서 국내 최대 통신사 입사의 문턱을 넘었습니다 기업과 부산시가 지역 청년을 IT 인재로 키우는 부산 디지털혁신아카데미 에서 교육을 받았는데 수업에서 배웠던 데이터 분석과 머신러닝 딥러닝을 실제 업무에서 활용하고 있습니다 이현진 부산디지털혁신아카데미 KT 에이블스쿨 수료생 정말 취업이 될 거라고는 예상하지 못해서 기뻤는데요 제가 직접 취업을 해보니까 정말 실무에 필요한 역량들을 가르쳐주더라고요 업무에 적응하기에 큰 어려움은 없을 것 같습니다 디지털혁신아카데미는 모든 과정을 각 기업이 직접 실무에 필요한 교육을 하고 교육비도 무료입니다 일대일 지도 수업이라 비전공자도 쉽게 따라갈 수 있습니다 우수한 성적으로 교육 과정을 수료하면 정규직 채용길도 열립니다 김서인 부산디지털혁신아카데미 교육생 아동복지학 전공 솔직히 이 직업에 대해서는 전공자가 아니면 혼자 공부해서 취직하기가 어려워요 여기서 배우는 커리큘럼에 있는 기술들이 현직에서 꼭 필요한 언어와 기술들이고 기업 역시 학벌과 전공에 상관없이 숨은 인재를 발굴 할 수 있어 만족하고 있습니다 김진 KT 에이블스쿨 교육 팀장 지난주 고용노동부 장관배 해커톤이라는 대회에서 부산이 대상을 받았어요 좋은 인재를 우리가 직접 가르치고 채용할 수 있다는 점 지역에 있는 인재들을 양성한다는 차원에서 부산디지털혁신아카데미 수료자의 취업률은 약 59 부산시는 더 많은 인재를 키우기 위해 한해 수강생 수를 2천 명으로 늘리고 대상도 부산 울산 경남으로 넓혔습니다 KBS 뉴스 강예슬입니다',
   '방송 2022년 7월 1일 금 이슈오늘 진행 박진형 이나연 출연 윤석천 경제평론가 오늘부터 유류세율 인하폭이 확대됐고 생애 최초 구매자를 대상으로 한 주택담보대출비율도 완화됐습니다 이밖에도 올해 하반기 달라지는 정책들이 더 있는데요 윤석천 경제평론가와 함께 하나씩 짚어보겠습니다 질문 1 오늘부터 유류세 인하 폭이 30 에서 37 로 확대됐습니다 국제유가 상승세가 계속되고 환율도 치솟고 있는데 인하효과를 체감할 수 있을까요 예비 유류세 37 인하 확대 첫날 실제는 16원 하락했습니다 왜 시차 발생하는가 질문 2 오늘부터 전기요금과 가스요금이 동시에 인상됩니다 이 소식에 요즘처럼 눅눅하고 무더운 날씨에도 에어컨을 켤까 말까 고민하는 분들 많을 것 같은데 요금 부담이 얼마나 늘어나는 건가요 질문 3 생애 최초로 주택을 구입할 경우 받을 수 있는 대출한도가 늘어납니다 본인의 명의로 집을 가져 본 적이 없다면 모두 생애 최초 주택 구입자 가 되는 건가요 예비 부동산 시장 안정 효과도 있을까 질문 3 1 빅스텝이다 자이언트스텝이다 요즘 많이 듣는 말이죠 집을 살 때 대출을 많이 받으면 좋겠지만 이처럼 기준금리가 인상될 것이란 전망 때문에 이자 부담을 걱정하지 않을 수 없을 것 같은데요 질문 4 앞으로 술이나 마약을 한 채 운전하다 사고를 냈다면 보험금 혜택을 받을 수 없고 운전자가 손실을 전액 부담해야 합니다 피해자들이 보상을 받지 못하는 경우는 없을까요 질문 5 오는 12일부터 교통법규도 달라집니다 벌점과 범칙금을 물지 않으려면 어떻게 바뀌는지 미리 숙지하고 있어야 할 것 같은데요 질문 6 오는 12일부터 주민등록증이 없이도 스마트폰만 있으면 신분 확인이 가능해집니다 실물 주민등록증과 효력이 같나요 질문 7 오늘부터 코로나 피해로 대출 상환에 어려움을 겪고 있는 소상공인과 자영업자를 위한 채무조정 프로그램이 시행됐다고 하는데 어떤 방식으로 빚을 감면해주는 건가요 질문 8 이달부터 군 장병 하루 급식비가 1만1000원에서 1만3000원으로 인상됩니다 장병 급식 질이 높아질 수 있는 정도인가요 질문 9 7월 첫날인 오늘 코스피가 장중 2300선 까지 붕괴했습니다',
   'img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오늘 1일 부터 유류세율 인하 폭이 확대됩니다 올해 3분기에는 생애최초 주택 구매 대출 규제도 완화됩니다 기획재정부에 따르면 정부는 계속되는 고유가 상황에 따라 국민의 유류비 부담 완화를 위해 이날부터 유류세를 법정 최대한도인 37 로 인하합니다 img tag s 사진 기획재정부 img tag e 기존 30 에서 대통령령으로 가능한 최대폭까지 확대한 겁니다 이에 따라 휘발유는 리터당 57원 경유는 38원 LPG는 12원 싸집니다 img tag s 사진 기획재정부 img tag e 또 오는 10월부터는 코로나19 피해로 대출상환에 어려움을 겪는 소상공인과 자영업자를 위한 채무조정 프로그램도 시행합니다 최대 30조원 규모로 소상공인 자영업자 새출발기금 가칭 을 설립해 대출채권 매입 등의 방식으로 상환일정 조정과 채무감면을 지원할 계획입니다 img tag s 사진 기획재정부 img tag e 부동산 대출 규제도 완화합니다 생애 최초 주택 구매자에 대해서는 LTV 상한을 주택 소재 지역이나 가격 소득과 상관없이 80 로 완화합니다 올해 3분기 중에 시행할 계획입니다 지금은 투기과열지구 경우 LTV가 60 까지 조정대상지역은 70 까지 적용되고 있습니다 이외에 올해 하반기에 바뀌는 정책은 기획재정부 홈페이지와 지자체 공공기관 등에서 확인할 수 있습니다']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'제목': '월 10만원 저축하면 정부가 10만원 더…18일부터 청년내일저축계좌 모집',
    '카테고리': '경제',
    '출처URL': 'https://n.news.naver.com/mnews/article/024/0000075873?sid=101'},
   {'출처URL': 'https://n.news.naver.com/mnews/article/003/0011280545?sid=101',
    '카테고리': '경제',
    '제목': '은행 가계대출 반년간 9조 넘게 줄었다'},
   {'출처URL': 'https://n.news.naver.com/mnews/article/056/0011295703?sid=101',
    '제목': '문과생도 IT 인재로 육성…취업률 59% ‘눈길’',
    '카테고리': '경제'},
   {'카테고리': '경제',
    '제목': '뉴스프라임 처음 집 사면 LTV 80%…하반기 달라지는 정책은',
    '출처URL': 'https://n.news.naver.com/mnews/article/422/0000549228?sid=101'},
   {'출처URL': 'https://n.news.naver.com/mnews/article/437/0000304023?sid=101',
    '제목': '오늘부터 유류세 인하 폭 확대…하반기 바뀌는 세제·금융 정책은',
    '카테고리': '경제'}]],
 'distances': [[0.6372470855712891,
   0.6379204988479614,
   0.6582581996917725,
   0.6816345453262329,
   0.6958054304122925]]}

In [56]:
result['documents'][0]

['보건복지부 제공 보건복지부는 저소득 청년에 저축액의 최대 3배까지 추가 적립해주는 청년내일저축계좌 가입자를 오는 18일부터 모집한다고 밝혔다 해당 제도는 월 10만원을 저축하면 정부가 지원금 월 10만원을 추가 적립하는 방식으로 3년간 지원해 청년의 자산 형성을 도와주는 청년특별대책제도다 참여자는 3년 만기 시 본인 납입액 360만원을 포함해 총 720만원과 예금이자를 수령하게 된다 청년내일저축계좌는 신청 시점 기준 만 19 34세인 청년이 대상이다 본인 소득 가구 소득 가구 재산 등 3가지 기준을 충족해야 한다 신청 당시에 근로 중이어야 하며 근로 사업소득이 50만원 초과 200만원 이하여야 한다 또한 자신이 속한 가구의 소득이 기준 중위소득 100 2022년 4인 가구 기준 512만1080원 이하여야 한다 가구 재산 기준은 지역에 따라 차등이 있다 대도시 3억5000만원 중소도시 2억원 농어촌 1억7000만원 이하인 가구가 대상이다 신청자가 기초생활수급자이거나 차상위계층 기준 중위소득 50 이하 이라면 혜택이 훨씬 크다 참여자가 10만원을 적립할 때마다 정부 지원금 30만원이 지급된다 3년 뒤 만기 때 총 1440만원의 적립금과 예금이자를 수령하게 된다 또한 가입 가능 연령이 만 15 39세로 더 넓으며 근로 사업소득기준도 면제된다 복지부는 그동안 청년층 대상 자산형성지원 사업을 해왔으나 그 대상이 수급자와 차상위계층에만 한정됐었다 그러나 이번에는 중위소득 100 이하인 청년으로 대상이 확대되면서 신청 대상이 지난해 1만8000명에서 올해 10만4000명으로 6배 증가했다 가입을 희망하는 청년은 복지로 홈페이지 www bokjiro go kr 를 통해 신청하면 된다 정부는 원활한 신청을 위해 신청 시작일인 18일부터 2주 7월 18 29일 간은 출생일 기준으로 5부제를 시행한다 5부제 기간에 신청하지 못한 경우 8월 1 5일에 생일과 무관하게 신청할 수 있다 대상자 선정 결과는 소득 재산 조사 등을 거쳐 10월 중에 발표된다 곽숙영 복지부 복지정책관은 이번 사업이 어려움을 겪고 있는 청년층에게 도움이 되기를 바라며 앞으로도 청년층을 적극 지원하기 위해 노력하겠다 고 말했다',
 '기사내용 요약 가계대출 잔액 699조6521억원 금리상승 자산시장 주춤 영향 하반기 규제 강화에 증가 전환 어려울 듯 서울 뉴시스 이주혜 기자 국내 주요 은행의 가계대출 잔액이 올해 상반기 감소한 것으로 나타났다 6개월간 9조원 이상이 줄었다 특히 신용대출이 8조원 넘게 줄면서 가계대출 감소세를 이끈 것으로 분석됐다 1일 은행권에 따르면 KB국민 신한 하나 우리 NH농협은행의 지난달 말 기준 가계대출 잔액은 699조6521억원으로 전월보다 1조4094억원 감소했다 가계대출 잔액이 700조원대 아래로 떨어진 것은 지난해 8월 이후 약 10개월 만이다 가계대출은 올해 1월부터 6개월 연속 감소세를 지속하면서 반년간 9조4008억원이 줄었다 은행권 관계자는 상반기 대출 감소는 금리 영향이 제일 크다고 볼 수 있다 며 자산시장도 상승세를 멈추면서 대출을 받아서 투자하는 수요가 사라졌다 실수요자가 아니면 대출을 받지 않는 분위기 라고 설명했다 주택담보대출은 지난달 소폭 늘면서 한 달 만에 증가했다 지난달 말 기준 주담대 잔액은 506조7714억원로 전월보다 991억원 늘었다 올해 들어 지난달까지 6개월간 주담대 잔액은 1조3668억원 늘어난 것으로 나타났다 지난해 하반기에는 한 달에만 3조원 이상 4조원까지도 늘어난 것과 비교하면 증가세가 둔화한 것이다 전월에는 감소세를 보이기도 했다 신용대출은 지난해 12월부터 지난달까지 꾸준히 줄면서 가계대출 감소세를 견인했다 올해에만 8조8783억원이 줄었다 지난달 말 신용대출 잔액은 130조6789억원으로 전월보다 1조1204억원이 감소했다 감소폭은 전월 6613억원 보다 커졌다 지난해까지만 해도 낮은 금리와 자산시장의 높은 수익률에 대출을 통한 영끌 로 투자에 나선 이들이 많았지만 금리가 가파르게 오르고 자산시장이 침체하면서 신용대출도 감소세를 지속하고 있다 집단대출은 지난달 말 기준 159조9421억원으로 전월 보다 3412억원 늘었다 4개월 연속 증가세를 지속했다 전세대출은 5개월 연속 늘었다 전월 대비 4479억원 늘어난 132조9061억원으로 집계됐다 전세대출 잔액은 올해 상반기 3조2092억원 증가했다 시중은행 관계자는 전세대출은 실수요자 중심이기 때문에 금리가 올라도 필요한 사람은 대출을 받을 수밖에 없다 면서 전셋값이 오르면 대출도 늘어나게 된다 고 설명했다 금리 상승이 계속되고 대출 관련 규제가 강화되면서 하반기에도 가계대출 감소 분위기는 크게 바뀌기 어려울 전망이다 은행권 관계자는 7월부터 총부채원리금상환비율 DSR 규제가 강화되고 금리도 오르다 보니 대출이 늘어날 이유가 없는 것 같다 면서 실수요자 중심으로는 지금과 같은 분위기를 반전시키기는 어려울 것 이라고 말했다',
 'KBS 부산 앵커 문과를 나와 죄송합니다 라는 자조적 말이 유행할 정도로 문과생의 취업 문턱은 갈수록 높아지는 상황인데요 기업이 직접 가르쳐서 뽑는 식으로 비전공자들도 IT 회사 취업이라는 벽을 허물고 있어 눈길을 끌고 있는데요 강예슬 기자가 보도합니다 리포트 동의대학교 중어중문학과를 졸업한 이현진 씨 지방대생에 비전공자라는 불리한 조건에서 국내 최대 통신사 입사의 문턱을 넘었습니다 기업과 부산시가 지역 청년을 IT 인재로 키우는 부산 디지털혁신아카데미 에서 교육을 받았는데 수업에서 배웠던 데이터 분석과 머신러닝 딥러닝을 실제 업무에서 활용하고 있습니다 이현진 부산디지털혁신아카데미 KT 에이블스쿨 수료생 정말 취업이 될 거라고는 예상하지 못해서 기뻤는데요 제가 직접 취업을 해보니까 정말 실무에 필요한 역량들을 가르쳐주더라고요 업무에 적응하기에 큰 어려움은 없을 것 같습니다 디지털혁신아카데미는 모든 과정을 각 기업이 직접 실무에 필요한 교육을 하고 교육비도 무료입니다 일대일 지도 수업이라 비전공자도 쉽게 따라갈 수 있습니다 우수한 성적으로 교육 과정을 수료하면 정규직 채용길도 열립니다 김서인 부산디지털혁신아카데미 교육생 아동복지학 전공 솔직히 이 직업에 대해서는 전공자가 아니면 혼자 공부해서 취직하기가 어려워요 여기서 배우는 커리큘럼에 있는 기술들이 현직에서 꼭 필요한 언어와 기술들이고 기업 역시 학벌과 전공에 상관없이 숨은 인재를 발굴 할 수 있어 만족하고 있습니다 김진 KT 에이블스쿨 교육 팀장 지난주 고용노동부 장관배 해커톤이라는 대회에서 부산이 대상을 받았어요 좋은 인재를 우리가 직접 가르치고 채용할 수 있다는 점 지역에 있는 인재들을 양성한다는 차원에서 부산디지털혁신아카데미 수료자의 취업률은 약 59 부산시는 더 많은 인재를 키우기 위해 한해 수강생 수를 2천 명으로 늘리고 대상도 부산 울산 경남으로 넓혔습니다 KBS 뉴스 강예슬입니다',
 '방송 2022년 7월 1일 금 이슈오늘 진행 박진형 이나연 출연 윤석천 경제평론가 오늘부터 유류세율 인하폭이 확대됐고 생애 최초 구매자를 대상으로 한 주택담보대출비율도 완화됐습니다 이밖에도 올해 하반기 달라지는 정책들이 더 있는데요 윤석천 경제평론가와 함께 하나씩 짚어보겠습니다 질문 1 오늘부터 유류세 인하 폭이 30 에서 37 로 확대됐습니다 국제유가 상승세가 계속되고 환율도 치솟고 있는데 인하효과를 체감할 수 있을까요 예비 유류세 37 인하 확대 첫날 실제는 16원 하락했습니다 왜 시차 발생하는가 질문 2 오늘부터 전기요금과 가스요금이 동시에 인상됩니다 이 소식에 요즘처럼 눅눅하고 무더운 날씨에도 에어컨을 켤까 말까 고민하는 분들 많을 것 같은데 요금 부담이 얼마나 늘어나는 건가요 질문 3 생애 최초로 주택을 구입할 경우 받을 수 있는 대출한도가 늘어납니다 본인의 명의로 집을 가져 본 적이 없다면 모두 생애 최초 주택 구입자 가 되는 건가요 예비 부동산 시장 안정 효과도 있을까 질문 3 1 빅스텝이다 자이언트스텝이다 요즘 많이 듣는 말이죠 집을 살 때 대출을 많이 받으면 좋겠지만 이처럼 기준금리가 인상될 것이란 전망 때문에 이자 부담을 걱정하지 않을 수 없을 것 같은데요 질문 4 앞으로 술이나 마약을 한 채 운전하다 사고를 냈다면 보험금 혜택을 받을 수 없고 운전자가 손실을 전액 부담해야 합니다 피해자들이 보상을 받지 못하는 경우는 없을까요 질문 5 오는 12일부터 교통법규도 달라집니다 벌점과 범칙금을 물지 않으려면 어떻게 바뀌는지 미리 숙지하고 있어야 할 것 같은데요 질문 6 오는 12일부터 주민등록증이 없이도 스마트폰만 있으면 신분 확인이 가능해집니다 실물 주민등록증과 효력이 같나요 질문 7 오늘부터 코로나 피해로 대출 상환에 어려움을 겪고 있는 소상공인과 자영업자를 위한 채무조정 프로그램이 시행됐다고 하는데 어떤 방식으로 빚을 감면해주는 건가요 질문 8 이달부터 군 장병 하루 급식비가 1만1000원에서 1만3000원으로 인상됩니다 장병 급식 질이 높아질 수 있는 정도인가요 질문 9 7월 첫날인 오늘 코스피가 장중 2300선 까지 붕괴했습니다',
 'img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오늘 1일 부터 유류세율 인하 폭이 확대됩니다 올해 3분기에는 생애최초 주택 구매 대출 규제도 완화됩니다 기획재정부에 따르면 정부는 계속되는 고유가 상황에 따라 국민의 유류비 부담 완화를 위해 이날부터 유류세를 법정 최대한도인 37 로 인하합니다 img tag s 사진 기획재정부 img tag e 기존 30 에서 대통령령으로 가능한 최대폭까지 확대한 겁니다 이에 따라 휘발유는 리터당 57원 경유는 38원 LPG는 12원 싸집니다 img tag s 사진 기획재정부 img tag e 또 오는 10월부터는 코로나19 피해로 대출상환에 어려움을 겪는 소상공인과 자영업자를 위한 채무조정 프로그램도 시행합니다 최대 30조원 규모로 소상공인 자영업자 새출발기금 가칭 을 설립해 대출채권 매입 등의 방식으로 상환일정 조정과 채무감면을 지원할 계획입니다 img tag s 사진 기획재정부 img tag e 부동산 대출 규제도 완화합니다 생애 최초 주택 구매자에 대해서는 LTV 상한을 주택 소재 지역이나 가격 소득과 상관없이 80 로 완화합니다 올해 3분기 중에 시행할 계획입니다 지금은 투기과열지구 경우 LTV가 60 까지 조정대상지역은 70 까지 적용되고 있습니다 이외에 올해 하반기에 바뀌는 정책은 기획재정부 홈페이지와 지자체 공공기관 등에서 확인할 수 있습니다']

In [57]:
context = "\n\n".join(result['documents'][0])   # 리스트 내용들을 \n\n과 함께 합쳐주는 기능! join 유용하게 잘 쓰자
print(context)

보건복지부 제공 보건복지부는 저소득 청년에 저축액의 최대 3배까지 추가 적립해주는 청년내일저축계좌 가입자를 오는 18일부터 모집한다고 밝혔다 해당 제도는 월 10만원을 저축하면 정부가 지원금 월 10만원을 추가 적립하는 방식으로 3년간 지원해 청년의 자산 형성을 도와주는 청년특별대책제도다 참여자는 3년 만기 시 본인 납입액 360만원을 포함해 총 720만원과 예금이자를 수령하게 된다 청년내일저축계좌는 신청 시점 기준 만 19 34세인 청년이 대상이다 본인 소득 가구 소득 가구 재산 등 3가지 기준을 충족해야 한다 신청 당시에 근로 중이어야 하며 근로 사업소득이 50만원 초과 200만원 이하여야 한다 또한 자신이 속한 가구의 소득이 기준 중위소득 100 2022년 4인 가구 기준 512만1080원 이하여야 한다 가구 재산 기준은 지역에 따라 차등이 있다 대도시 3억5000만원 중소도시 2억원 농어촌 1억7000만원 이하인 가구가 대상이다 신청자가 기초생활수급자이거나 차상위계층 기준 중위소득 50 이하 이라면 혜택이 훨씬 크다 참여자가 10만원을 적립할 때마다 정부 지원금 30만원이 지급된다 3년 뒤 만기 때 총 1440만원의 적립금과 예금이자를 수령하게 된다 또한 가입 가능 연령이 만 15 39세로 더 넓으며 근로 사업소득기준도 면제된다 복지부는 그동안 청년층 대상 자산형성지원 사업을 해왔으나 그 대상이 수급자와 차상위계층에만 한정됐었다 그러나 이번에는 중위소득 100 이하인 청년으로 대상이 확대되면서 신청 대상이 지난해 1만8000명에서 올해 10만4000명으로 6배 증가했다 가입을 희망하는 청년은 복지로 홈페이지 www bokjiro go kr 를 통해 신청하면 된다 정부는 원활한 신청을 위해 신청 시작일인 18일부터 2주 7월 18 29일 간은 출생일 기준으로 5부제를 시행한다 5부제 기간에 신청하지 못한 경우 8월 1 5일에 생일과 무관하게 신청할 수 있다 대상자 선정 결과는 소득 재산 조사 등을 거쳐 10월 중에 발표된다 곽숙영 복지부 복지정책관은 이번 사업이 어려움을 겪고 있는 청년층에게 도움이 되기를 바라며 앞으로도 청년층을 적극 지원하기 위해 노력하겠다 고 말했다

기사내용 요약 가계대출 잔액 699조6521억원 금리상승 자산시장 주춤 영향 하반기 규제 강화에 증가 전환 어려울 듯 서울 뉴시스 이주혜 기자 국내 주요 은행의 가계대출 잔액이 올해 상반기 감소한 것으로 나타났다 6개월간 9조원 이상이 줄었다 특히 신용대출이 8조원 넘게 줄면서 가계대출 감소세를 이끈 것으로 분석됐다 1일 은행권에 따르면 KB국민 신한 하나 우리 NH농협은행의 지난달 말 기준 가계대출 잔액은 699조6521억원으로 전월보다 1조4094억원 감소했다 가계대출 잔액이 700조원대 아래로 떨어진 것은 지난해 8월 이후 약 10개월 만이다 가계대출은 올해 1월부터 6개월 연속 감소세를 지속하면서 반년간 9조4008억원이 줄었다 은행권 관계자는 상반기 대출 감소는 금리 영향이 제일 크다고 볼 수 있다 며 자산시장도 상승세를 멈추면서 대출을 받아서 투자하는 수요가 사라졌다 실수요자가 아니면 대출을 받지 않는 분위기 라고 설명했다 주택담보대출은 지난달 소폭 늘면서 한 달 만에 증가했다 지난달 말 기준 주담대 잔액은 506조7714억원로 전월보다 991억원 늘었다 올해 들어 지난달까지 6개월간 주담대 잔액은 1조3668억원 늘어난 것으로 나타났다 지난해 하반기에는 한 달에만 3조원 이상 4조원까지도 늘어난 것과 비교하면 증가세가 둔화한 것이다 전월에는 감소세를 보이기도 했다 신용대출은 지난해 12월부터 지난달까지 꾸준히 줄면서 가계대출 감소세를 견인했다 올해에만 8조8783억원이 줄었다 지난달 말 신용대출 잔액은 130조6789억원으로 전월보다 1조1204억원이 감소했다 감소폭은 전월 6613억원 보다 커졌다 지난해까지만 해도 낮은 금리와 자산시장의 높은 수익률에 대출을 통한 영끌 로 투자에 나선 이들이 많았지만 금리가 가파르게 오르고 자산시장이 침체하면서 신용대출도 감소세를 지속하고 있다 집단대출은 지난달 말 기준 159조9421억원으로 전월 보다 3412억원 늘었다 4개월 연속 증가세를 지속했다 전세대출은 5개월 연속 늘었다 전월 대비 4479억원 늘어난 132조9061억원으로 집계됐다 전세대출 잔액은 올해 상반기 3조2092억원 증가했다 시중은행 관계자는 전세대출은 실수요자 중심이기 때문에 금리가 올라도 필요한 사람은 대출을 받을 수밖에 없다 면서 전셋값이 오르면 대출도 늘어나게 된다 고 설명했다 금리 상승이 계속되고 대출 관련 규제가 강화되면서 하반기에도 가계대출 감소 분위기는 크게 바뀌기 어려울 전망이다 은행권 관계자는 7월부터 총부채원리금상환비율 DSR 규제가 강화되고 금리도 오르다 보니 대출이 늘어날 이유가 없는 것 같다 면서 실수요자 중심으로는 지금과 같은 분위기를 반전시키기는 어려울 것 이라고 말했다

KBS 부산 앵커 문과를 나와 죄송합니다 라는 자조적 말이 유행할 정도로 문과생의 취업 문턱은 갈수록 높아지는 상황인데요 기업이 직접 가르쳐서 뽑는 식으로 비전공자들도 IT 회사 취업이라는 벽을 허물고 있어 눈길을 끌고 있는데요 강예슬 기자가 보도합니다 리포트 동의대학교 중어중문학과를 졸업한 이현진 씨 지방대생에 비전공자라는 불리한 조건에서 국내 최대 통신사 입사의 문턱을 넘었습니다 기업과 부산시가 지역 청년을 IT 인재로 키우는 부산 디지털혁신아카데미 에서 교육을 받았는데 수업에서 배웠던 데이터 분석과 머신러닝 딥러닝을 실제 업무에서 활용하고 있습니다 이현진 부산디지털혁신아카데미 KT 에이블스쿨 수료생 정말 취업이 될 거라고는 예상하지 못해서 기뻤는데요 제가 직접 취업을 해보니까 정말 실무에 필요한 역량들을 가르쳐주더라고요 업무에 적응하기에 큰 어려움은 없을 것 같습니다 디지털혁신아카데미는 모든 과정을 각 기업이 직접 실무에 필요한 교육을 하고 교육비도 무료입니다 일대일 지도 수업이라 비전공자도 쉽게 따라갈 수 있습니다 우수한 성적으로 교육 과정을 수료하면 정규직 채용길도 열립니다 김서인 부산디지털혁신아카데미 교육생 아동복지학 전공 솔직히 이 직업에 대해서는 전공자가 아니면 혼자 공부해서 취직하기가 어려워요 여기서 배우는 커리큘럼에 있는 기술들이 현직에서 꼭 필요한 언어와 기술들이고 기업 역시 학벌과 전공에 상관없이 숨은 인재를 발굴 할 수 있어 만족하고 있습니다 김진 KT 에이블스쿨 교육 팀장 지난주 고용노동부 장관배 해커톤이라는 대회에서 부산이 대상을 받았어요 좋은 인재를 우리가 직접 가르치고 채용할 수 있다는 점 지역에 있는 인재들을 양성한다는 차원에서 부산디지털혁신아카데미 수료자의 취업률은 약 59 부산시는 더 많은 인재를 키우기 위해 한해 수강생 수를 2천 명으로 늘리고 대상도 부산 울산 경남으로 넓혔습니다 KBS 뉴스 강예슬입니다

방송 2022년 7월 1일 금 이슈오늘 진행 박진형 이나연 출연 윤석천 경제평론가 오늘부터 유류세율 인하폭이 확대됐고 생애 최초 구매자를 대상으로 한 주택담보대출비율도 완화됐습니다 이밖에도 올해 하반기 달라지는 정책들이 더 있는데요 윤석천 경제평론가와 함께 하나씩 짚어보겠습니다 질문 1 오늘부터 유류세 인하 폭이 30 에서 37 로 확대됐습니다 국제유가 상승세가 계속되고 환율도 치솟고 있는데 인하효과를 체감할 수 있을까요 예비 유류세 37 인하 확대 첫날 실제는 16원 하락했습니다 왜 시차 발생하는가 질문 2 오늘부터 전기요금과 가스요금이 동시에 인상됩니다 이 소식에 요즘처럼 눅눅하고 무더운 날씨에도 에어컨을 켤까 말까 고민하는 분들 많을 것 같은데 요금 부담이 얼마나 늘어나는 건가요 질문 3 생애 최초로 주택을 구입할 경우 받을 수 있는 대출한도가 늘어납니다 본인의 명의로 집을 가져 본 적이 없다면 모두 생애 최초 주택 구입자 가 되는 건가요 예비 부동산 시장 안정 효과도 있을까 질문 3 1 빅스텝이다 자이언트스텝이다 요즘 많이 듣는 말이죠 집을 살 때 대출을 많이 받으면 좋겠지만 이처럼 기준금리가 인상될 것이란 전망 때문에 이자 부담을 걱정하지 않을 수 없을 것 같은데요 질문 4 앞으로 술이나 마약을 한 채 운전하다 사고를 냈다면 보험금 혜택을 받을 수 없고 운전자가 손실을 전액 부담해야 합니다 피해자들이 보상을 받지 못하는 경우는 없을까요 질문 5 오는 12일부터 교통법규도 달라집니다 벌점과 범칙금을 물지 않으려면 어떻게 바뀌는지 미리 숙지하고 있어야 할 것 같은데요 질문 6 오는 12일부터 주민등록증이 없이도 스마트폰만 있으면 신분 확인이 가능해집니다 실물 주민등록증과 효력이 같나요 질문 7 오늘부터 코로나 피해로 대출 상환에 어려움을 겪고 있는 소상공인과 자영업자를 위한 채무조정 프로그램이 시행됐다고 하는데 어떤 방식으로 빚을 감면해주는 건가요 질문 8 이달부터 군 장병 하루 급식비가 1만1000원에서 1만3000원으로 인상됩니다 장병 급식 질이 높아질 수 있는 정도인가요 질문 9 7월 첫날인 오늘 코스피가 장중 2300선 까지 붕괴했습니다

img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오늘 1일 부터 유류세율 인하 폭이 확대됩니다 올해 3분기에는 생애최초 주택 구매 대출 규제도 완화됩니다 기획재정부에 따르면 정부는 계속되는 고유가 상황에 따라 국민의 유류비 부담 완화를 위해 이날부터 유류세를 법정 최대한도인 37 로 인하합니다 img tag s 사진 기획재정부 img tag e 기존 30 에서 대통령령으로 가능한 최대폭까지 확대한 겁니다 이에 따라 휘발유는 리터당 57원 경유는 38원 LPG는 12원 싸집니다 img tag s 사진 기획재정부 img tag e 또 오는 10월부터는 코로나19 피해로 대출상환에 어려움을 겪는 소상공인과 자영업자를 위한 채무조정 프로그램도 시행합니다 최대 30조원 규모로 소상공인 자영업자 새출발기금 가칭 을 설립해 대출채권 매입 등의 방식으로 상환일정 조정과 채무감면을 지원할 계획입니다 img tag s 사진 기획재정부 img tag e 부동산 대출 규제도 완화합니다 생애 최초 주택 구매자에 대해서는 LTV 상한을 주택 소재 지역이나 가격 소득과 상관없이 80 로 완화합니다 올해 3분기 중에 시행할 계획입니다 지금은 투기과열지구 경우 LTV가 60 까지 조정대상지역은 70 까지 적용되고 있습니다 이외에 올해 하반기에 바뀌는 정책은 기획재정부 홈페이지와 지자체 공공기관 등에서 확인할 수 있습니다

#### ChromaDB 저장하기

In [58]:
# 저장소 생성
persistent_client = chromadb.PersistentClient(path="./news_chroma_db")

In [59]:
# 컬렉션 만들기
saved_collection = persistent_client.get_or_create_collection(
    name="news_collection",
    embedding_function=embeddings,
    configuration={"hnsw" : {"space" : "cosine"}}
)

In [60]:
# 마지막 적재
saved_collection.upsert(ids=ids,
                        documents=docs,
                        metadatas=metadata)

#### ChromaDB 불러오기
- 이전에 저장한 DB 불러와서 저장하기

In [ ]:
load_client = chromadb.PersistentClient(path="news_chroma_db")
load_collection = load_client.get_collection(
    name="news_collection",
    embedding_function=embeddings   # configuration 어차피 안바뀌니 적을 필요 X, 임베딩도 또 하는건 아니지만 뭘 썼는지 알려주기 위해
)

In [65]:
load_collection.count()

200

In [ ]:
load_collection.query(query_texts=["가계 대출 소식에 대해 알려줘"], n_results=5)

{'ids': [['51', '127', '188', '108', '89']],
 'embeddings': None,
 'documents': [['기사내용 요약 가계대출 잔액 699조6521억원 금리상승 자산시장 주춤 영향 하반기 규제 강화에 증가 전환 어려울 듯 서울 뉴시스 이주혜 기자 국내 주요 은행의 가계대출 잔액이 올해 상반기 감소한 것으로 나타났다 6개월간 9조원 이상이 줄었다 특히 신용대출이 8조원 넘게 줄면서 가계대출 감소세를 이끈 것으로 분석됐다 1일 은행권에 따르면 KB국민 신한 하나 우리 NH농협은행의 지난달 말 기준 가계대출 잔액은 699조6521억원으로 전월보다 1조4094억원 감소했다 가계대출 잔액이 700조원대 아래로 떨어진 것은 지난해 8월 이후 약 10개월 만이다 가계대출은 올해 1월부터 6개월 연속 감소세를 지속하면서 반년간 9조4008억원이 줄었다 은행권 관계자는 상반기 대출 감소는 금리 영향이 제일 크다고 볼 수 있다 며 자산시장도 상승세를 멈추면서 대출을 받아서 투자하는 수요가 사라졌다 실수요자가 아니면 대출을 받지 않는 분위기 라고 설명했다 주택담보대출은 지난달 소폭 늘면서 한 달 만에 증가했다 지난달 말 기준 주담대 잔액은 506조7714억원로 전월보다 991억원 늘었다 올해 들어 지난달까지 6개월간 주담대 잔액은 1조3668억원 늘어난 것으로 나타났다 지난해 하반기에는 한 달에만 3조원 이상 4조원까지도 늘어난 것과 비교하면 증가세가 둔화한 것이다 전월에는 감소세를 보이기도 했다 신용대출은 지난해 12월부터 지난달까지 꾸준히 줄면서 가계대출 감소세를 견인했다 올해에만 8조8783억원이 줄었다 지난달 말 신용대출 잔액은 130조6789억원으로 전월보다 1조1204억원이 감소했다 감소폭은 전월 6613억원 보다 커졌다 지난해까지만 해도 낮은 금리와 자산시장의 높은 수익률에 대출을 통한 영끌 로 투자에 나선 이들이 많았지만 금리가 가파르게 오르고 자산시장이 침체하면서 신용대출도 감소세를 지속하고 있다 집단대출은 지난달 말 기준 159조9421억원으로 전월 보다 3412억원 늘었다 4개월 연속 증가세를 지속했다 전세대출은 5개월 연속 늘었다 전월 대비 4479억원 늘어난 132조9061억원으로 집계됐다 전세대출 잔액은 올해 상반기 3조2092억원 증가했다 시중은행 관계자는 전세대출은 실수요자 중심이기 때문에 금리가 올라도 필요한 사람은 대출을 받을 수밖에 없다 면서 전셋값이 오르면 대출도 늘어나게 된다 고 설명했다 금리 상승이 계속되고 대출 관련 규제가 강화되면서 하반기에도 가계대출 감소 분위기는 크게 바뀌기 어려울 전망이다 은행권 관계자는 7월부터 총부채원리금상환비율 DSR 규제가 강화되고 금리도 오르다 보니 대출이 늘어날 이유가 없는 것 같다 면서 실수요자 중심으로는 지금과 같은 분위기를 반전시키기는 어려울 것 이라고 말했다',
   '원 달러 환율 3 2원 오른 1300 2원 마감 미국발 경기침체 우려 부각 원화 약세 압력 강화 글로벌 경기 침체 우려에 우리나라 경제 버팀목인 수출이 꺾일 것이란 관측에 힘이 실리면서 5일 원 달러 환율이 1300원을 넘어 상승 마감했다 이날 서울외환시장에서 원 달러 환율은 전 거래일보다 3 2원 오른 1300 2원에 마감했다 이날 1 1원 내린 1296원에 출발한 환율은 오후 들어 상승폭을 키우면서 한때 1301 2원까지 고점을 높였다 환율이 종가 기준으로 1300원을 넘어선 것은 지난달 23일 1301 8원 이후 8거래일 만이다 이날 환율은 미국 유럽연합 EU 일본 등 주요국을 중심으로 경기 침체 공포가 확산되면서 투자자금이 안전자산인 달러화로 몰린 데 힘입어 상승했다고 전문가들은 설명했다 대기하던 수입업체 결제 수요 등이 몰린 점도 영향을 미쳤다 5일 서울 중구 하나은행 위변조대응센터에서 직원이 달러를 정리하고 있다 백석현 신한은행 연구원은 미국 등 주요국의 경기 침체 전망은 한국 수출의 급격한 감소 가능성을 시사한다 며 원화 가치에 영향을 미치는 가장 큰 요인이 수출인데 수출이 꺾일 일만 남았다 는 불안 심리가 확산되면서 트레이더들이 달러 매수에 적극 나선 것으로 보인다 고 말했다 시장에서는 미국을 중심으로 경기침체 그림자가 짙어지고 있다는 분석이 나오고 있다 세계 경제가 인플레이션 지속적인 물가 상승 에 시달리는 가운데 미국 연방준비제도 Fed 연준 가 공격적인 금리인상에 나서면서 경기가 급속도로 냉각될 수 있다는 분석이다 미국의 GDP 전망을 실시간으로 제시하는 애틀랜타연방준비은행의 GDP 나우 예측 모델은 지난 1일 현지시각 미국의 올해 2분기 국내총생산 GDP 성장률을 2 1 로 전망했다 1분기 경제성장률이 1 6 를 기록한 데 이어 2분기 연속 마이너스 성장을 예고한 것이다 일본 투자은행 노무라는 미국과 EU 영국 일본 호주 캐나다 한국 등이 12개월 안에 경기후퇴에 진입할 것이라고 예측했다 노무라는 세계 경제가 동반 성장 둔화에 진입하고 있다는 신호가 증가하고 있다 며 더는 성장을 위해 수출 회복에 기댈 수 없음을 의미한다 고 진단했다 이에 따라 우리나라 하반기 수출 전망도 악화됐다 추경호 경제부총리 겸 기획재정부 장관은 지난 3일 열린 3차 비상경제장관회의에서 주력 품목의 수출 성장세가 둔화할 우려가 있어 하반기 수출 상황도 낙관하기 어렵다 고 말했다 백석현 연구원은 전 세계적으로 스태그플레이션 물가 상승을 동반한 경기침체 압력이 커진 점은 원화 가치에 부정적이다 라며 수출 둔화 우려 등에 따른 원화 약세 압력이 상당 기간 지속되면서 원 달러 환율도 당분간 1300원대에서 움직일 것으로 예상한다 고 했다',
   '이데일리 양지윤 기자 기가레인이 경영관리 효율성 제고 차원에서 자회사 흡수합병을 결정했단 소식에 장 초반 강세다 4일 마켓포인트에 따르면 오전 9시4분 현재 기가레인 049080 은 전 거래일보다 7 28 오른 1620원에 거래되고 있다 기가레인은 지난 1일 100 자회사인 씨텍과 소규모 합병을 결정했다고 공시했다 합병회사인 기가레인은 존속하고 피합병회사인 씨텍은 소멸하게 된다 합병 기일은 오는 9월5일이다 회사 측은 합병 완료 후 기가레인은 신주를 발행하지 않고 최대주주 변경도 없다고 설명했다 합병비율은 1대0이다 회사측은 경영관리 효율성 제고를 위한 것 이라고 밝혔다',
   '전거래일보다 29 76 서울경제 이화전기 024810 가 배터리 시장 진출을 추진한다는 소식에 상한가를 기록했다 4일 오전 9시 23분 한국거래소에 따르면 이화전기는 전거래일보다 29 76 오른 1330원에 거래되고 있다 이화전기가 배터리 시장 진출을 추진한다는 소식이 주가를 끌어올린 것으로 보인다 이날 이화전기는 지난 달 27일 한국을 방문한 에너테크인터내셔널 이사회 의장을 만나 사업협력의 구체적인 방안에 대해 논의했다고 밝혔다',
   '바클레이스 경상흑자 900억달러 늘어 위안화 1 8 절상 미국의 성조기와 중국의 오성홍기 AFP 뉴스1 서울 뉴스1 신기림 기자 미국이 대중 관세를 철폐해도 미국의 인플레이션과 중국 위안화에 미치는 영향력은 크지 않을 것 modest 이라고 바클레이스가 전망했다 5일 블룸버그에 따르면 바클레이스 애널리스트들은 대중 관세가 완전히 사라져도 미국의 인플레이션에 직접 미치는 효과는 최대 한 차례로 0 3 포인트 p 낮추는 데에 그칠 것이라고 예상했다 미국의 소비재 항목 바스켓 에서 중국산이 차지하는 비중이 상대적으로 작기 때문이라고 관세 철폐가 인플레이션에 미치는 영향력이 크지 않다고 바클레이스는 설명했다 대중관세 철폐가 미국 인플레이션에 끼치는 영향력은 양동이의 물 한 방울 drop in the bucket 즈음 되겠다고 바클레이스 애널리스트들은 표현했다 또 미국의 통화정책을 숙고하는 데에 미치는 영향력도 없을 것이라고 예상했다 관세를 부분적으로만 철폐하면 인플레이션 압박을 낮추는 효과는 더 작을 것이라고 바클레이스는 지적했다 미국과 중국 사이 무역 긴장이 잠재적으로 해소될 가능성에도 중국 위안화가 고속충전 supercharger 될 것 같지도 않다고 바클레이스는 지적했다 관세가 양국에서 모두 철폐되면 중국의 경상흑자는 900억달러 늘어날 것이라고 바클레이스 애널리스트들은 추산했다 이는 위안화 가치를 1 8 끌어 올리는 효과지만 관세가 단계적이고 부분적으로 철폐될 가능성이 높은 만큼 위안화 절상효과는 그 보다 작을 것이라고 바클레이스는 전망했다 또 위안화의 급격한 절상은 안정적 환율관리를 원하는 중앙은행 인민은행도 원하지 않는 바일 것이라고 바클레이스는 예상했다 블룸버그 월스트리트저널 WSJ 등 주요 경제매체에 따르면 조 바이든 미국 대통령은 이번주 일부 대중 관세를 철폐한다고 공식적으로 발표할 것으로 보인다 류허 중국 부총리와 재닛 옐런 미국 재무장관은 5일 경제 제재 관세와 관련해 화상회의를 가졌다고 양국 정부는 밝혔다']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'시군구명': '창원시 마산합포구',
    '시도명': '경상남도',
    '출처URL': 'https://n.news.naver.com/mnews/article/003/0011280545?sid=101',
    '카테고리': '경제',
    '도서관명': '마산도서관',
    '제목': '은행 가계대출 반년간 9조 넘게 줄었다'},
   {'시도명': '전남광주통합특별시',
    '시군구명': '무안군',
    '제목': '韓 수출 전망 악화에 원·달러 환율 1300원 재돌파',
    '출처URL': 'https://n.news.naver.com/mnews/article/366/0000825510?sid=101',
    '카테고리': '경제',
    '도서관명': '사랑으로열린(작은)도서관'},
   {'제목': '특징주기가레인 자회사 씨텍 흡수합병 결정에 7%대↑',
    '시군구명': '남구',
    '도서관명': '에코시티작은도서관',
    '출처URL': 'https://n.news.naver.com/mnews/article/018/0005258964?sid=101',
    '시도명': '전남광주통합특별시',
    '카테고리': '경제'},
   {'카테고리': '경제',
    '출처URL': 'https://n.news.naver.com/mnews/article/011/0004072127?sid=101',
    '도서관명': '대중 작은도서관',
    '제목': '특징주 이화전기 배터리 시장 진출 시동 걸자 상한가',
    '시도명': '전남광주통합특별시',
    '시군구명': '무안군'},
   {'출처URL': 'https://n.news.naver.com/mnews/article/421/0006198698?sid=101',
    '카테고리': '경제',
    '시도명': '인천광역시',
    '시군구명': '제물포구',
    '도서관명': '인천광역시교육청화도진도서관',
    '제목': '대중관세 철폐시 美 인플레 0.3%p 효과에 그칠 것'}]],
 'distances': [[0.54222571849823,
   0.5795128345489502,
   0.6071807146072388,
   0.6191989183425903,
   0.6317170858383179]]}

### Qdrant
- 방식은 거의 chromadb와 동일

In [62]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

In [63]:
qdrant = QdrantClient(path="./qdrant_news_db")   # 메모리에 하려면 ":memory:"
qdrant

RuntimeError: Storage folder ./qdrant_news_db is already accessed by another instance of Qdrant client. If you require concurrent access, use Qdrant server instead.

In [ ]:
qdrant.create_collection(
    collection_name="news_qdrant",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE)
)

True

### 문서 적재
- 문서를 포인트 단위로 넣는 방식
- id, vector, playload(부가정보 = 메타데이터 + 원문)

In [ ]:
client = OpenAI()

response = client.embeddings.create(
    model="text-embedding-3-small",
    input=docs
)

In [ ]:
response.data[0].embedding

[-0.020660400390625,
 -0.0028591156005859375,
 0.034210205078125,
 0.034271240234375,
 0.01126861572265625,
 0.0037384033203125,
 0.0038433074951171875,
 0.0570068359375,
 -0.0007305145263671875,
 -0.059722900390625,
 -0.034515380859375,
 -0.0190277099609375,
 0.0014085769653320312,
 -0.04046630859375,
 0.0245513916015625,
 -0.011505126953125,
 -0.004791259765625,
 -0.0009984970092773438,
 0.0478515625,
 -0.012451171875,
 -0.0214691162109375,
 -0.02880859375,
 0.01332855224609375,
 0.006488800048828125,
 -0.007358551025390625,
 -0.018646240234375,
 0.01395416259765625,
 0.0479736328125,
 -0.0010051727294921875,
 -0.01537322998046875,
 -0.03497314453125,
 -0.03692626953125,
 0.0318603515625,
 0.015472412109375,
 0.0149078369140625,
 0.0260772705078125,
 0.0093994140625,
 0.0213623046875,
 0.0309295654296875,
 -0.00678253173828125,
 0.03057861328125,
 -0.006877899169921875,
 0.003173828125,
 0.004497528076171875,
 0.0196990966796875,
 0.0259857177734375,
 -0.0028095245361328125,
 0.001773834228515625,
 0.05328369140625,
 0.0225830078125,
 0.048675537109375,
 0.005176544189453125,
 0.0172119140625,
 -0.05963134765625,
 -0.0228729248046875,
 0.00550079345703125,
 -0.04766845703125,
 -0.010711669921875,
 -0.0032291412353515625,
 0.004589080810546875,
 0.058624267578125,
 -0.03082275390625,
 0.0263824462890625,
 0.05084228515625,
 0.024627685546875,
 0.009521484375,
 0.057373046875,
 -0.01442718505859375,
 -0.0086822509765625,
 0.0284423828125,
 -0.00067138671875,
 0.0164337158203125,
 0.057281494140625,
 0.0203094482421875,
 -0.007305145263671875,
 -0.0234527587890625,
 -0.0036106109619140625,
 0.0126953125,
 0.004650115966796875,
 -0.0016565322875976562,
 0.0548095703125,
 -0.0022735595703125,
 0.0230712890625,
 0.0225372314453125,
 -0.0310211181640625,
 0.01232147216796875,
 -0.0272674560546875,
 -0.007495880126953125,
 -0.01507568359375,
 0.06768798828125,
 0.01300048828125,
 0.034149169921875,
 0.03094482421875,
 0.03057861328125,
 0.0196685791015625,
 -0.004985809326171875,
 -0.044281005859375,
 0.0005297660827636719,
 0.0517578125,
 0.06707763671875,
 -0.01404571533203125,
 -0.053436279296875,
 0.0275115966796875,
 -0.046478271484375,
 0.039459228515625,
 0.00916290283203125,
 0.051483154296875,
 -0.034393310546875,
 0.005970001220703125,
 -0.005748748779296875,
 0.0081787109375,
 -0.004421234130859375,
 0.016082763671875,
 0.0278472900390625,
 0.036956787109375,
 -0.047454833984375,
 0.04998779296875,
 -0.038726806640625,
 0.000949859619140625,
 0.015045166015625,
 0.0033092498779296875,
 0.0113983154296875,
 -0.003505706787109375,
 -0.013671875,
 -0.0340576171875,
 0.019805908203125,
 -0.005580902099609375,
 -0.0137786865234375,
 -0.06793212890625,
 -0.0367431640625,
 -0.044464111328125,
 -0.028411865234375,
 -0.018768310546875,
 -0.038970947265625,
 0.047393798828125,
 0.0230865478515625,
 -0.06805419921875,
 -0.047454833984375,
 -0.025787353515625,
 -0.052581787109375,
 0.041229248046875,
 -0.0132598876953125,
 0.04730224609375,
 0.001834869384765625,
 -0.0161285400390625,
 -0.01519775390625,
 0.014007568359375,
 0.00583648681640625,
 -0.0313720703125,
 0.05938720703125,
 -0.0124053955078125,
 -0.0137939453125,
 0.0221405029296875,
 -0.06878662109375,
 -0.0011444091796875,
 -0.005741119384765625,
 -0.0250091552734375,
 0.0540771484375,
 -0.00399017333984375,
 0.0006003379821777344,
 0.01508331298828125,
 -0.0093841552734375,
 -0.0080718994140625,
 0.00728607177734375,
 0.041168212890625,
 0.01145172119140625,
 -0.036590576171875,
 0.0222015380859375,
 -0.051513671875,
 0.01030731201171875,
 0.0240325927734375,
 0.05615234375,
 0.039459228515625,
 0.07763671875,
 0.0023555755615234375,
 0.0212860107421875,
 0.052001953125,
 0.027099609375,
 -0.0188140869140625,
 0.0150909423828125,
 0.00970458984375,
 0.01300048828125,
 -0.0014400482177734375,
 0.0252532958984375,
 -0.0204925537109375,
 -0.032318115234375,
 0.0301055908203125,
 -0.052093505859375,
 0.0222930908203125,
 0.07513427734375,
 -0.045745849609375,
 0.035186767578125,
 0.00890350341796875,
 0.032562255859375,
 -0.007564544677734375,
 -0.017120361328125,
 -0.01335906982421875,
 0.0231170654296875,
 -0.01073455810546875,
 0.0032901763916015625,
 -0.0286102294921875,
 -0.0086212158203125,
 0.0208740234375,
 -0.00765228271484375,
 -0.022796630859375,
 -0.011199951171875,
 0.01395416259765625,
 -0.0036487579345703125,
 0.019134521484375,
 0.011322021484375,
 0.0343017578125,
 -0.0169525146484375,
 -0.00798797607421875,
 0.044769287109375,
 0.0124969482421875,
 -0.0654296875,
 -0.037384033203125,
 0.04718017578125,
 -0.06134033203125,
 -0.0196380615234375,
 0.038604736328125,
 0.046844482421875,
 0.0164947509765625,
 0.055206298828125,
 -0.020538330078125,
 0.0066070556640625,
 -0.002933502197265625,
 -0.0275421142578125,
 -0.0254669189453125,
 -0.0144500732421875,
 0.005245208740234375,
 -0.0003535747528076172,
 -0.036163330078125,
 0.0215911865234375,
 0.038116455078125,
 -0.004241943359375,
 0.0226593017578125,
 -0.0048828125,
 -0.00885009765625,
 0.014617919921875,
 0.04058837890625,
 0.058197021484375,
 0.05487060546875,
 0.034393310546875,
 0.0088958740234375,
 0.0262298583984375,
 0.005237579345703125,
 -0.039642333984375,
 -0.0191192626953125,
 0.06622314453125,
 0.006206512451171875,
 0.07275390625,
 0.041473388671875,
 0.01702880859375,
 -0.02056884765625,
 -0.00429534912109375,
 -0.0107421875,
 0.0556640625,
 -0.0296630859375,
 0.0092926025390625,
 0.00800323486328125,
 0.0162811279296875,
 0.037139892578125,
 -0.00731658935546875,
 -0.0168609619140625,
 0.04412841796875,
 0.006267547607421875,
 0.07696533203125,
 -0.00630950927734375,
 0.006870269775390625,
 -0.034820556640625,
 -0.03955078125,
 -0.0192718505859375,
 -0.051300048828125,
 -0.007232666015625,
 -0.003986358642578125,
 -0.045166015625,
 0.0114593505859375,
 -0.0003643035888671875,
 -0.0217437744140625,
 0.001712799072265625,
 0.00563812255859375,
 -0.0181427001953125,
 -0.0263519287109375,
 -0.0248260498046875,
 0.04205322265625,
 -0.0673828125,
 0.0250701904296875,
 -0.022796630859375,
 0.015380859375,
 0.01549530029296875,
 -0.0311431884765625,
 -0.0013256072998046875,
 -0.0302734375,
 -0.08233642578125,
 0.011016845703125,
 -0.01255035400390625,
 -0.061981201171875,
 -0.032440185546875,
 -0.014404296875,
 -0.0029163360595703125,
 -0.0213165283203125,
 -0.0309295654296875,
 -0.0024852752685546875,
 -0.00533294677734375,
 0.035369873046875,
 -0.038299560546875,
 0.038055419921875,
 0.040313720703125,
 0.020233154296875,
 -0.0184783935546875,
 -0.014923095703125,
 -0.005619049072265625,
 -0.01258087158203125,
 -0.004566192626953125,
 -0.0296630859375,
 0.041412353515625,
 0.0311431884765625,
 -0.0029449462890625,
 0.00576019287109375,
 0.023651123046875,
 -0.0279083251953125,
 0.0103607177734375,
 -0.052337646484375,
 -0.0019989013671875,
 0.009613037109375,
 0.0247039794921875,
 -0.01122283935546875,
 -0.00928497314453125,
 -0.0260162353515625,
 0.00910186767578125,
 0.021087646484375,
 0.017913818359375,
 0.01421356201171875,
 0.0171051025390625,
 -0.053466796875,
 -0.01348876953125,
 0.045166015625,
 0.035430908203125,
 -0.024078369140625,
 -0.0258026123046875,
 -0.01265716552734375,
 -0.0158233642578125,
 -0.039276123046875,
 0.03546142578125,
 -0.049591064453125,
 0.04718017578125,
 -0.0234222412109375,
 0.0005044937133789062,
 0.027435302734375,
 0.003662109375,
 -0.0212554931640625,
 0.005863189697265625,
 0.020660400390625,
 0.0059661865234375,
 -0.06396484375,
 -0.0372314453125,
 0.055938720703125,
 -0.03302001953125,
 0.0098114013671875,
 0.031494140625,
 -0.035003662109375,
 0.023406982421875,
 0.040618896484375,
 0.042327880859375,
 -0.01052093505859375,
 -0.0025234222412109375,
 0.01116180419921875,
 0.008087158203125,
 0.04425048828125,
 -0.0211944580078125,
 0.003570556640625,
 0.0188751220703125,
 0.007770538330078125,
 -0.026153564453125,
 0.0274658203125,
 0.0181732177734375,
 0.0277557373046875,
 -0.01471710205078125,
 -0.0325927734375,
 -0.002979278564453125,
 -0.03387451171875,
 -0.00748443603515625,
 -0.0382080078125,
 0.0004925727844238281,
 -0.007579803466796875,
 -0.010528564453125,
 0.004665374755859375,
 -0.007701873779296875,
 0.0271453857421875,
 0.040985107421875,
 -0.0282440185546875,
 0.017333984375,
 -0.020416259765625,
 -0.02008056640625,
 0.001316070556640625,
 0.0157470703125,
 0.0027561187744140625,
 -0.029815673828125,
 -0.006488800048828125,
 0.01470947265625,
 -0.046966552734375,
 0.0165557861328125,
 0.025970458984375,
 -0.0323486328125,
 -0.0301361083984375,
 0.0035076141357421875,
 -0.0296630859375,
 0.01910400390625,
 -0.033477783203125,
 0.035186767578125,
 -0.048126220703125,
 0.0229644775390625,
 -0.0237274169921875,
 -0.0498046875,
 -0.03485107421875,
 -0.0287933349609375,
 0.0030078887939453125,
 -0.00914764404296875,
 0.01297760009765625,
 0.00460052490234375,
 0.01342010498046875,
 -0.0142822265625,
 0.041656494140625,
 0.0300140380859375,
 -0.01708984375,
 -0.047454833984375,
 0.030731201171875,
 0.00014412403106689453,
 -0.03204345703125,
 -0.025390625,
 -0.09423828125,
 -0.011199951171875,
 -0.033966064453125,
 0.00238037109375,
 0.056365966796875,
 -0.0010690689086914062,
 0.007221221923828125,
 0.0170745849609375,
 0.01364898681640625,
 0.0092010498046875,
 0.002834320068359375,
 0.0019626617431640625,
 0.00995635986328125,
 -0.0494384765625,
 0.025054931640625,
 0.01763916015625,
 0.020233154296875,
 -0.026092529296875,
 0.0268096923828125,
 0.0080718994140625,
 -0.027069091796875,
 -0.0260009765625,
 0.00365447998046875,
 -0.037994384765625,
 0.01407623291015625,
 -0.0121307373046875,
 -0.0087432861328125,
 0.04791259765625,
 -0.037994384765625,
 0.034271240234375,
 0.0400390625,
 0.0088043212890625,
 0.0224456787109375,
 0.0167999267578125,
 -0.0138702392578125,
 0.0022792816162109375,
 0.0504150390625,
 0.003185272216796875,
 -0.0276336669921875,
 0.0345458984375,
 -0.01678466796875,
 0.0107879638671875,
 0.03167724609375,
 0.01102447509765625,
 -0.043487548828125,
 -0.01505279541015625,
 0.005443572998046875,
 -0.0087890625,
 0.01031494140625,
 -0.02850341796875,
 -0.048797607421875,
 -0.0243988037109375,
 -0.0222930908203125,
 0.0309295654296875,
 -0.01268768310546875,
 0.0201416015625,
 -0.0411376953125,
 0.027679443359375,
 -0.0537109375,
 -0.02349853515625,
 0.05865478515625,
 0.05316162109375,
 -0.002353668212890625,
 0.01947021484375,
 0.0302734375,
 -0.03887939453125,
 -0.009857177734375,
 -0.0187835693359375,
 0.01194000244140625,
 0.0226287841796875,
 -0.035858154296875,
 -0.0148773193359375,
 -0.0203857421875,
 0.013671875,
 -0.008514404296875,
 -0.047332763671875,
 -0.0164947509765625,
 0.034759521484375,
 -0.019989013671875,
 0.0394287109375,
 0.002185821533203125,
 -0.0100250244140625,
 0.0155792236328125,
 0.0300750732421875,
 0.0149993896484375,
 0.013916015625,
 0.0217437744140625,
 0.0297698974609375,
 0.0251617431640625,
 -0.01337432861328125,
 -0.004238128662109375,
 -0.0033245086669921875,
 -0.00811767578125,
 0.0367431640625,
 -0.014068603515625,
 -0.0204010009765625,
 -0.034698486328125,
 0.01303863525390625,
 0.0185699462890625,
 -0.032958984375,
 0.004505157470703125,
 0.0202178955078125,
 -0.0212554931640625,
 0.021820068359375,
 -0.01800537109375,
 0.0246429443359375,
 -0.017120361328125,
 0.0029735565185546875,
 0.0023746490478515625,
 0.003498077392578125,
 -0.0067291259765625,
 0.044769287109375,
 -0.046661376953125,
 0.0020771026611328125,
 -0.006191253662109375,
 -0.006015777587890625,
 -0.0128173828125,
 0.026885986328125,
 0.012786865234375,
 0.04400634765625,
 0.002315521240234375,
 -0.03448486328125,
 0.0180816650390625,
 0.018524169921875,
 0.036376953125,
 0.0129547119140625,
 -0.015289306640625,
 0.051422119140625,
 0.006160736083984375,
 0.0205535888671875,
 0.00855255126953125,
 0.01003265380859375,
 0.0111236572265625,
 -0.025634765625,
 -0.017974853515625,
 0.04180908203125,
 0.01910400390625,
 -0.0289306640625,
 0.01422119140625,
 0.0062255859375,
 -0.00757598876953125,
 -0.0008912086486816406,
 0.01715087890625,
 -0.0008625984191894531,
 -0.004215240478515625,
 0.0012426376342773438,
 -0.032135009765625,
 0.0156402587890625,
 -0.0260162353515625,
 0.00110626220703125,
 -0.008056640625,
 0.049163818359375,
 -0.0091400146484375,
 -0.0164794921875,
 0.020050048828125,
 0.00909423828125,
 0.0019626617431640625,
 0.022125244140625,
 0.01812744140625,
 -0.0467529296875,
 0.0068511962890625,
 0.0211944580078125,
 -0.023712158203125,
 0.035186767578125,
 -0.0227813720703125,
 -0.0269317626953125,
 -0.0260467529296875,
 0.057159423828125,
 0.0062713623046875,
 0.003910064697265625,
 -0.03546142578125,
 0.01568603515625,
 -0.034637451171875,
 -0.028411865234375,
 -0.07012939453125,
 0.019561767578125,
 -0.021240234375,
 -0.0188751220703125,
 -0.026580810546875,
 0.0030517578125,
 0.01922607421875,
 -0.0219879150390625,
 0.01366424560546875,
 -0.0174102783203125,
 0.0258941650390625,
 -0.032867431640625,
 0.0153350830078125,
 0.0235595703125,
 -0.049835205078125,
 0.005096435546875,
 0.0105743408203125,
 0.02044677734375,
 -0.0133819580078125,
 0.00994873046875,
 -0.0047454833984375,
 0.0012083053588867188,
 0.0294952392578125,
 -0.026458740234375,
 -0.01363372802734375,
 -0.004974365234375,
 -0.0198211669921875,
 0.028839111328125,
 -0.032562255859375,
 0.006061553955078125,
 0.034393310546875,
 -0.0087127685546875,
 0.0289154052734375,
 -0.0102081298828125,
 0.03436279296875,
 0.0091552734375,
 -0.004467010498046875,
 -0.0171966552734375,
 -0.03216552734375,
 0.004703521728515625,
 0.02783203125,
 0.02984619140625,
 -0.0191497802734375,
 0.0204010009765625,
 -0.00923919677734375,
 0.00653076171875,
 0.0208892822265625,
 -0.031707763671875,
 0.01490020751953125,
 0.01499176025390625,
 0.005580902099609375,
 -0.0094146728515625,
 0.0203857421875,
 0.00911712646484375,
 0.05194091796875,
 -0.006023406982421875,
 0.00798797607421875,
 0.004215240478515625,
 -0.0090179443359375,
 -0.003814697265625,
 0.0072021484375,
 0.0221405029296875,
 0.0307769775390625,
 0.01068115234375,
 0.0277557373046875,
 -0.01462554931640625,
 -0.014862060546875,
 0.03570556640625,
 0.018829345703125,
 -0.00104522705078125,
 0.0218658447265625,
 -0.006305694580078125,
 -0.01323699951171875,
 -0.00855255126953125,
 -0.027740478515625,
 0.051361083984375,
 0.0083465576171875,
 0.005352020263671875,
 -0.042816162109375,
 0.00762176513671875,
 -0.0184783935546875,
 -4.673004150390625e-05,
 0.0085906982421875,
 -0.01488494873046875,
 -0.03912353515625,
 -0.017486572265625,
 0.007110595703125,
 0.00946807861328125,
 0.03497314453125,
 -0.006122589111328125,
 -0.050811767578125,
 0.0279693603515625,
 0.01421356201171875,
 0.029022216796875,
 0.0109405517578125,
 0.047515869140625,
 -0.007640838623046875,
 -0.00133514404296875,
 -0.00528717041015625,
 0.01177978515625,
 -0.0020389556884765625,
 -0.005069732666015625,
 -0.005603790283203125,
 0.02685546875,
 -0.01352691650390625,
 -0.0244140625,
 -0.004909515380859375,
 -0.01076507568359375,
 -0.08782958984375,
 0.0274200439453125,
 0.007495880126953125,
 -0.004180908203125,
 -0.005741119384765625,
 0.0309906005859375,
 0.0193634033203125,
 -0.030609130859375,
 -0.0263824462890625,
 -0.016693115234375,
 -0.051971435546875,
 -0.031982421875,
 0.004337310791015625,
 0.022308349609375,
 0.01332855224609375,
 -0.0171966552734375,
 -0.01258087158203125,
 0.0243377685546875,
 0.0226287841796875,
 -0.050140380859375,
 -0.00890350341796875,
 0.0256805419921875,
 0.033294677734375,
 -0.0362548828125,
 0.003383636474609375,
 -0.00591278076171875,
 -0.00286102294921875,
 0.03271484375,
 -0.0011157989501953125,
 -0.0036678314208984375,
 0.0286712646484375,
 -0.0465087890625,
 -0.018280029296875,
 0.0100555419921875,
 0.023345947265625,
 -0.04974365234375,
 0.04864501953125,
 0.01611328125,
 -0.0004639625549316406,
 -3.635883331298828e-05,
 0.03515625,
 0.01018524169921875,
 -0.0292510986328125,
 -0.00013506412506103516,
 0.0025386810302734375,
 -0.00904083251953125,
 0.0193328857421875,
 0.048248291015625,
 0.0223846435546875,
 -0.023468017578125,
 0.0247650146484375,
 0.043121337890625,
 0.0499267578125,
 -0.018035888671875,
 0.00972747802734375,
 -0.0738525390625,
 0.018798828125,
 0.0248870849609375,
 -0.00815582275390625,
 0.056488037109375,
 -0.03143310546875,
 -0.01116180419921875,
 0.005680084228515625,
 0.0205841064453125,
 -0.04473876953125,
 -0.023529052734375,
 -0.01032257080078125,
 -0.0132598876953125,
 0.00185394287109375,
 0.055877685546875,
 0.030242919921875,
 0.0338134765625,
 -0.0195465087890625,
 0.0258331298828125,
 -0.02069091796875,
 0.03564453125,
 -0.049285888671875,
 0.01837158203125,
 0.0105743408203125,
 0.0362548828125,
 0.0030574798583984375,
 0.0280609130859375,
 0.032135009765625,
 -0.044097900390625,
 0.01277923583984375,
 0.01558685302734375,
 0.010162353515625,
 -0.0266571044921875,
 0.00951385498046875,
 0.043243408203125,
 0.010498046875,
 0.0009036064147949219,
 0.039825439453125,
 -0.0277099609375,
 -0.0184326171875,
 -0.0119171142578125,
 -0.0211181640625,
 0.0011882781982421875,
 0.00655364990234375,
 0.021881103515625,
 -0.050079345703125,
 -0.0296783447265625,
 -0.0027675628662109375,
 0.0030364990234375,
 0.00739288330078125,
 -0.016387939453125,
 -0.0188140869140625,
 -0.030975341796875,
 -0.0005235671997070312,
 0.0014715194702148438,
 0.00936126708984375,
 0.00827789306640625,
 0.003314971923828125,
 -0.060150146484375,
 0.0167388916015625,
 -0.0286712646484375,
 -0.0007123947143554688,
 -0.00025582313537597656,
 -0.0178985595703125,
 -0.00429534912109375,
 -0.0013523101806640625,
 0.0225067138671875,
 0.0086212158203125,
 0.0272064208984375,
 0.037384033203125,
 0.0003037452697753906,
 -0.049652099609375,
 -0.0272979736328125,
 -0.02825927734375,
 0.00957489013671875,
 0.0055694580078125,
 -0.01544189453125,
 0.01369476318359375,
 0.0303955078125,
 -0.00969696044921875,
 -0.04425048828125,
 -0.002979278564453125,
 0.016143798828125,
 0.014862060546875,
 0.027801513671875,
 -0.001865386962890625,
 -0.01483154296875,
 -0.003643035888671875,
 0.00036907196044921875,
 0.00223541259765625,
 0.0062103271484375,
 -0.02349853515625,
 -0.01342010498046875,
 -0.0256500244140625,
 0.034942626953125,
 -0.0023479461669921875,
 -0.007137298583984375,
 0.006626129150390625,
 -0.0092315673828125,
 0.006053924560546875,
 0.044281005859375,
 0.017913818359375,
 -0.03204345703125,
 -0.0237274169921875,
 -0.01216888427734375,
 -0.008819580078125,
 0.03228759765625,
 0.01216888427734375,
 -0.00466156005859375,
 0.0069427490234375,
 -0.026824951171875,
 -0.020416259765625,
 0.029388427734375,
 -0.00827789306640625,
 -0.01090240478515625,
 0.025970458984375,
 -0.00951385498046875,
 0.0293426513671875,
 0.0005269050598144531,
 -0.0074005126953125,
 0.0003409385681152344,
 0.0176849365234375,
 0.01512908935546875,
 0.00310516357421875,
 0.028411865234375,
 -0.0205535888671875,
 -0.050201416015625,
 -0.0054779052734375,
 -0.00298309326171875,
 -0.016265869140625,
 -0.01467132568359375,
 0.006198883056640625,
 -0.045684814453125,
 -0.007289886474609375,
 0.0064697265625,
 -0.029266357421875,
 -0.002552032470703125,
 -0.01087188720703125,
 0.007053375244140625,
 0.00206756591796875,
 0.03900146484375,
 0.0043182373046875,
 -0.017181396484375,
 0.012939453125,
 0.0018396377563476562,
 -0.0184783935546875,
 0.0132293701171875,
 -0.02264404296875,
 -0.0191497802734375,
 0.01629638671875,
 0.03057861328125,
 0.0053558349609375,
 -0.01739501953125,
 0.0194549560546875,
 -0.036102294921875,
 -0.0318603515625,
 0.01229095458984375,
 0.019378662109375,
 0.00768280029296875,
 -0.0099029541015625,
 0.0010280609130859375,
 0.0216522216796875,
 -0.0110015869140625,
 -0.01580810546875,
 0.038330078125,
 0.006481170654296875,
 -0.001102447509765625,
 0.0254669189453125,
 0.01739501953125,
 0.0017423629760742188,
 0.0087738037109375,
 0.0086212158203125,
 -0.03363037109375,
 -0.0014657974243164062,
 -0.021575927734375,
 0.0126190185546875,
 -0.0142974853515625,
 -0.048675537109375,
 -0.0311431884765625,
 -0.005130767822265625,
 -0.0183258056640625,
 0.0159149169921875,

In [ ]:
points = []

for i in range(len(docs)):
    points.append(PointStruct(
        id=i,
        vector=response.data[i].embedding,
        payload={'제목' : df['제목'][i],
                 '카테고리' : df['카테고리'][i]}

    ))

In [ ]:
points[:5]

[PointStruct(id=0, vector=[-0.020660400390625, -0.0028591156005859375, 0.034210205078125, 0.034271240234375, 0.01126861572265625, 0.0037384033203125, 0.0038433074951171875, 0.0570068359375, -0.0007305145263671875, -0.059722900390625, -0.034515380859375, -0.0190277099609375, 0.0014085769653320312, -0.04046630859375, 0.0245513916015625, -0.011505126953125, -0.004791259765625, -0.0009984970092773438, 0.0478515625, -0.012451171875, -0.0214691162109375, -0.02880859375, 0.01332855224609375, 0.006488800048828125, -0.007358551025390625, -0.018646240234375, 0.01395416259765625, 0.0479736328125, -0.0010051727294921875, -0.01537322998046875, -0.03497314453125, -0.03692626953125, 0.0318603515625, 0.015472412109375, 0.0149078369140625, 0.0260772705078125, 0.0093994140625, 0.0213623046875, 0.0309295654296875, -0.00678253173828125, 0.03057861328125, -0.006877899169921875, 0.003173828125, 0.004497528076171875, 0.0196990966796875, 0.0259857177734375, -0.0028095245361328125, 0.001773834228515625, 0.05328369140625, 0.0225830078125, 0.048675537109375, 0.005176544189453125, 0.0172119140625, -0.05963134765625, -0.0228729248046875, 0.00550079345703125, -0.04766845703125, -0.010711669921875, -0.0032291412353515625, 0.004589080810546875, 0.058624267578125, -0.03082275390625, 0.0263824462890625, 0.05084228515625, 0.024627685546875, 0.009521484375, 0.057373046875, -0.01442718505859375, -0.0086822509765625, 0.0284423828125, -0.00067138671875, 0.0164337158203125, 0.057281494140625, 0.0203094482421875, -0.007305145263671875, -0.0234527587890625, -0.0036106109619140625, 0.0126953125, 0.004650115966796875, -0.0016565322875976562, 0.0548095703125, -0.0022735595703125, 0.0230712890625, 0.0225372314453125, -0.0310211181640625, 0.01232147216796875, -0.0272674560546875, -0.007495880126953125, -0.01507568359375, 0.06768798828125, 0.01300048828125, 0.034149169921875, 0.03094482421875, 0.03057861328125, 0.0196685791015625, -0.004985809326171875, -0.044281005859375, 0.0005297660827636719, 0.0517578125, 0.06707763671875, -0.01404571533203125, -0.053436279296875, 0.0275115966796875, -0.046478271484375, 0.039459228515625, 0.00916290283203125, 0.051483154296875, -0.034393310546875, 0.005970001220703125, -0.005748748779296875, 0.0081787109375, -0.004421234130859375, 0.016082763671875, 0.0278472900390625, 0.036956787109375, -0.047454833984375, 0.04998779296875, -0.038726806640625, 0.000949859619140625, 0.015045166015625, 0.0033092498779296875, 0.0113983154296875, -0.003505706787109375, -0.013671875, -0.0340576171875, 0.019805908203125, -0.005580902099609375, -0.0137786865234375, -0.06793212890625, -0.0367431640625, -0.044464111328125, -0.028411865234375, -0.018768310546875, -0.038970947265625, 0.047393798828125, 0.0230865478515625, -0.06805419921875, -0.047454833984375, -0.025787353515625, -0.052581787109375, 0.041229248046875, -0.0132598876953125, 0.04730224609375, 0.001834869384765625, -0.0161285400390625, -0.01519775390625, 0.014007568359375, 0.00583648681640625, -0.0313720703125, 0.05938720703125, -0.0124053955078125, -0.0137939453125, 0.0221405029296875, -0.06878662109375, -0.0011444091796875, -0.005741119384765625, -0.0250091552734375, 0.0540771484375, -0.00399017333984375, 0.0006003379821777344, 0.01508331298828125, -0.0093841552734375, -0.0080718994140625, 0.00728607177734375, 0.041168212890625, 0.01145172119140625, -0.036590576171875, 0.0222015380859375, -0.051513671875, 0.01030731201171875, 0.0240325927734375, 0.05615234375, 0.039459228515625, 0.07763671875, 0.0023555755615234375, 0.0212860107421875, 0.052001953125, 0.027099609375, -0.0188140869140625, 0.0150909423828125, 0.00970458984375, 0.01300048828125, -0.0014400482177734375, 0.0252532958984375, -0.0204925537109375, -0.032318115234375, 0.0301055908203125, -0.052093505859375, 0.0222930908203125, 0.07513427734375, -0.045745849609375, 0.035186767578125, 0.00890350341796875, 0.032562255859375, -0.007564544677734375, -0.017120361328125, -0.01335906982421875, 0.0231170654296875, -0.01073455810546875, 0.0032901763916015625, -0.0286102294921875, -0.0086212158203125, 0.0208740234375, -0.00765228271484375, -0.022796630859375, -0.011199951171875, 0.01395416259765625, -0.0036487579345703125, 0.019134521484375, 0.011322021484375, 0.0343017578125, -0.0169525146484375, -0.00798797607421875, 0.044769287109375, 0.0124969482421875, -0.0654296875, -0.037384033203125, 0.04718017578125, -0.06134033203125, -0.0196380615234375, 0.038604736328125, 0.046844482421875, 0.0164947509765625, 0.055206298828125, -0.020538330078125, 0.0066070556640625, -0.002933502197265625, -0.0275421142578125, -0.0254669189453125, -0.0144500732421875, 0.005245208740234375, -0.0003535747528076172, -0.036163330078125, 0.0215911865234375, 0.038116455078125, -0.004241943359375, 0.0226593017578125, -0.0048828125, -0.00885009765625, 0.014617919921875, 0.04058837890625, 0.058197021484375, 0.05487060546875, 0.034393310546875, 0.0088958740234375, 0.0262298583984375, 0.005237579345703125, -0.039642333984375, -0.0191192626953125, 0.06622314453125, 0.006206512451171875, 0.07275390625, 0.041473388671875, 0.01702880859375, -0.02056884765625, -0.00429534912109375, -0.0107421875, 0.0556640625, -0.0296630859375, 0.0092926025390625, 0.00800323486328125, 0.0162811279296875, 0.037139892578125, -0.00731658935546875, -0.0168609619140625, 0.04412841796875, 0.006267547607421875, 0.07696533203125, -0.00630950927734375, 0.006870269775390625, -0.034820556640625, -0.03955078125, -0.0192718505859375, -0.051300048828125, -0.007232666015625, -0.003986358642578125, -0.045166015625, 0.0114593505859375, -0.0003643035888671875, -0.0217437744140625, 0.001712799072265625, 0.00563812255859375, -0.0181427001953125, -0.0263519287109375, -0.0248260498046875, 0.04205322265625, -0.0673828125, 0.0250701904296875, -0.022796630859375, 0.015380859375, 0.01549530029296875, -0.0311431884765625, -0.0013256072998046875, -0.0302734375, -0.08233642578125, 0.011016845703125, -0.01255035400390625, -0.061981201171875, -0.032440185546875, -0.014404296875, -0.0029163360595703125, -0.0213165283203125, -0.0309295654296875, -0.0024852752685546875, -0.00533294677734375, 0.035369873046875, -0.038299560546875, 0.038055419921875, 0.040313720703125, 0.020233154296875, -0.0184783935546875, -0.014923095703125, -0.005619049072265625, -0.01258087158203125, -0.004566192626953125, -0.0296630859375, 0.041412353515625, 0.0311431884765625, -0.0029449462890625, 0.00576019287109375, 0.023651123046875, -0.0279083251953125, 0.0103607177734375, -0.052337646484375, -0.0019989013671875, 0.009613037109375, 0.0247039794921875, -0.01122283935546875, -0.00928497314453125, -0.0260162353515625, 0.00910186767578125, 0.021087646484375, 0.017913818359375, 0.01421356201171875, 0.0171051025390625, -0.053466796875, -0.01348876953125, 0.045166015625, 0.035430908203125, -0.024078369140625, -0.0258026123046875, -0.01265716552734375, -0.0158233642578125, -0.039276123046875, 0.03546142578125, -0.049591064453125, 0.04718017578125, -0.0234222412109375, 0.0005044937133789062, 0.027435302734375, 0.003662109375, -0.0212554931640625, 0.005863189697265625, 0.020660400390625, 0.0059661865234375, -0.06396484375, -0.0372314453125, 0.055938720703125, -0.03302001953125, 0.0098114013671875, 0.031494140625, -0.035003662109375, 0.023406982421875, 0.040618896484375, 0.042327880859375, -0.01052093505859375, -0.0025234222412109375, 0.01116180419921875, 0.008087158203125, 0.04425048828125, -0.0211944580078125, 0.003570556640625, 0.0188751220703125, 0.007770538330078125, -0.026153564453125, 0.0274658203125, 0.0181732177734375, 0.0277557373046875, -0.01471710205078125, -0.0325927734375, -0.002979278564453125, -0.03387451171875, -0.00748443603515625, -0.0382080078125, 0.0004925727844238281, -0.007579803466796875, -0.010528564453125, 0.004665374755859375, -0.007701873779296875, 0.0271453857421875, 0.040985107421875, -0.0282440185546875, 0.017333984375, -0.020416259765625, -0.02008056640625, 0.001316070556640625, 0.0157470703125, 0.0027561187744140625, -0.029815673828125, -0.006488800048828125, 0.01470947265625, -0.046966552734375, 0.0165557861328125, 0.025970458984375, -0.0323486328125, -0.0301361083984375, 0.0035076141357421875, -0.0296630859375, 0.01910400390625, -0.033477783203125, 0.035186767578125, -0.048126220703125, 0.0229644775390625, -0.0237274169921875, -0.0498046875, -0.03485107421875, -0.0287933349609375, 0.0030078887939453125, -0.00914764404296875, 0.01297760009765625, 0.00460052490234375, 0.01342010498046875, -0.0142822265625, 0.041656494140625, 0.0300140380859375, -0.01708984375, -0.047454833984375, 0.030731201171875, 0.00014412403106689453, -0.03204345703125, -0.025390625, -0.09423828125, -0.011199951171875, -0.033966064453125, 0.00238037109375, 0.056365966796875, -0.0010690689086914062, 0.007221221923828125, 0.0170745849609375, 0.01364898681640625, 0.0092010498046875, 0.002834320068359375, 0.0019626617431640625, 0.00995635986328125, -0.0494384765625, 0.025054931640625, 0.01763916015625, 0.020233154296875, -0.026092529296875, 0.0268096923828125, 0.0080718994140625, -0.027069091796875, -0.0260009765625, 0.00365447998046875, -0.037994384765625, 0.01407623291015625, -0.0121307373046875, -0.0087432861328125, 0.04791259765625, -0.037994384765625, 0.034271240234375, 0.0400390625, 0.0088043212890625, 0.0224456787109375, 0.0167999267578125, -0.0138702392578125, 0.0022792816162109375, 0.0504150390625, 0.003185272216796875, -0.0276336669921875, 0.0345458984375, -0.01678466796875, 0.0107879638671875, 0.03167724609375, 0.01102447509765625, -0.043487548828125, -0.01505279541015625, 0.005443572998046875, -0.0087890625, 0.01031494140625, -0.02850341796875, -0.048797607421875, -0.0243988037109375, -0.0222930908203125, 0.0309295654296875, -0.01268768310546875, 0.0201416015625, -0.0411376953125, 0.027679443359375, -0.0537109375, -0.02349853515625, 0.05865478515625, 0.05316162109375, -0.002353668212890625, 0.01947021484375, 0.0302734375, -0.03887939453125, -0.009857177734375, -0.0187835693359375, 0.01194000244140625, 0.0226287841796875, -0.035858154296875, -0.0148773193359375, -0.0203857421875, 0.013671875, -0.008514404296875, -0.047332763671875, -0.0164947509765625, 0.034759521484375, -0.019989013671875, 0.0394287109375, 0.002185821533203125, -0.0100250244140625, 0.0155792236328125, 0.0300750732421875, 0.0149993896484375, 0.013916015625, 0.0217437744140625, 0.0297698974609375, 0.0251617431640625, -0.01337432861328125, -0.004238128662109375, -0.0033245086669921875, -0.00811767578125, 0.0367431640625, -0.014068603515625, -0.0204010009765625, -0.034698486328125, 0.01303863525390625, 0.0185699462890625, -0.032958984375, 0.004505157470703125, 0.0202178955078125, -0.0212554931640625, 0.021820068359375, -0.01800537109375, 0.0246429443359375, -0.017120361328125, 0.0029735565185546875, 0.0023746490478515625, 0.003498077392578125, -0.0067291259765625, 0.044769287109375, -0.046661376953125, 0.0020771026611328125, -0.006191253662109375, -0.006015777587890625, -0.0128173828125, 0.026885986328125, 0.012786865234375, 0.04400634765625, 0.002315521240234375, -0.03448486328125, 0.0180816650390625, 0.018524169921875, 0.036376953125, 0.0129547119140625, -0.015289306640625, 0.051422119140625, 0.006160736083984375, 0.0205535888671875, 0.00855255126953125, 0.01003265380859375, 0.0111236572265625, -0.025634765625, -0.017974853515625, 0.04180908203125, 0.01910400390625, -0.0289306640625, 0.01422119140625, 0.0062255859375, -0.00757598876953125, -0.0008912086486816406, 0.01715087890625, -0.0008625984191894531, -0.004215240478515625, 0.0012426376342773438, -0.032135009765625, 0.0156402587890625, -0.0260162353515625, 0.00110626220703125, -0.008056640625, 0.049163818359375, -0.0091400146484375, -0.0164794921875, 0.020050048828125, 0.00909423828125, 0.0019626617431640625, 0.022125244140625, 0.01812744140625, -0.0467529296875, 0.0068511962890625, 0.0211944580078125, -0.023712158203125, 0.035186767578125, -0.0227813720703125, -0.0269317626953125, -0.0260467529296875, 0.057159423828125, 0.0062713623046875, 0.003910064697265625, -0.03546142578125, 0.01568603515625, -0.034637451171875, -0.028411865234375, -0.07012939453125, 0.019561767578125, -0.021240234375, -0.0188751220703125, -0.026580810546875, 0.0030517578125, 0.01922607421875, -0.0219879150390625, 0.01366424560546875, -0.0174102783203125, 0.0258941650390625, -0.032867431640625, 0.0153350830078125, 0.0235595703125, -0.049835205078125, 0.005096435546875, 0.0105743408203125, 0.02044677734375, -0.0133819580078125, 0.00994873046875, -0.0047454833984375, 0.0012083053588867188, 0.0294952392578125, -0.026458740234375, -0.01363372802734375, -0.004974365234375, -0.0198211669921875, 0.028839111328125, -0.032562255859375, 0.006061553955078125, 0.034393310546875, -0.0087127685546875, 0.0289154052734375, -0.0102081298828125, 0.03436279296875, 0.0091552734375, -0.004467010498046875, -0.0171966552734375, -0.03216552734375, 0.004703521728515625, 0.02783203125, 0.02984619140625, -0.0191497802734375, 0.0204010009765625, -0.00923919677734375, 0.00653076171875, 0.0208892822265625, -0.031707763671875, 0.01490020751953125, 0.01499176025390625, 0.005580902099609375, -0.0094146728515625, 0.0203857421875, 0.00911712646484375, 0.05194091796875, -0.006023406982421875, 0.00798797607421875, 0.004215240478515625, -0.0090179443359375, -0.003814697265625, 0.0072021484375, 0.0221405029296875, 0.0307769775390625, 0.01068115234375, 0.0277557373046875, -0.01462554931640625, -0.014862060546875, 0.03570556640625, 0.018829345703125, -0.00104522705078125, 0.0218658447265625, -0.006305694580078125, -0.01323699951171875, -0.00855255126953125, -0.027740478515625, 0.051361083984375, 0.0083465576171875, 0.005352020263671875, -0.042816162109375, 0.00762176513671875, -0.0184783935546875, -4.673004150390625e-05, 0.0085906982421875, -0.01488494873046875, -0.03912353515625, -0.017486572265625, 0.007110595703125, 0.00946807861328125, 0.03497314453125, -0.006122589111328125, -0.050811767578125, 0.0279693603515625, 0.01421356201171875, 0.029022216796875, 0.0109405517578125, 0.047515869140625, -0.007640838623046875, -0.00133514404296875, -0.00528717041015625, 0.01177978515625, -0.0020389556884765625, -0.005069732666015625, -0.005603790283203125, 0.02685546875, -0.01352691650390625, -0.0244140625, -0.004909515380859375, -0.01076507568359375, -0.08782958984375, 0.0274200439453125, 0.007495880126953125, -0.004180908203125, -0.005741119384765625, 0.0309906005859375, 0.0193634033203125, -0.030609130859375, -0.0263824462890625, -0.016693115234375, -0.051971435546875, -0.031982421875, 0.004337310791015625, 0.022308349609375, 0.01332855224609375, -0.0171966552734375, -0.01258087158203125, 0.0243377685546875, 0.0226287841796875, -0.050140380859375, -0.00890350341796875, 0.0256805419921875, 0.033294677734375, -0.0362548828125, 0.003383636474609375, -0.00591278076171875, -0.00286102294921875, 0.03271484375, -0.0011157989501953125, -0.0036678314208984375, 0.0286712646484375, -0.0465087890625, -0.018280029296875, 0.0100555419921875, 0.023345947265625, -0.04974365234375, 0.04864501953125, 0.01611328125, -0.0004639625549316406, -3.635883331298828e-05, 0.03515625, 0.01018524169921875, -0.0292510986328125, -0.00013506412506103516, 0.0025386810302734375, -0.00904083251953125, 0.0193328857421875, 0.048248291015625, 0.0223846435546875, -0.023468017578125, 0.0247650146484375, 0.043121337890625, 0.0499267578125, -0.018035888671875, 0.00972747802734375, -0.0738525390625, 0.018798828125, 0.0248870849609375, -0.00815582275390625, 0.056488037109375, -0.03143310546875, -0.01116180419921875, 0.005680084228515625, 0.0205841064453125, -0.04473876953125, -0.023529052734375, -0.01032257080078125, -0.0132598876953125, 0.00185394287109375, 0.055877685546875, 0.030242919921875, 0.0338134765625, -0.0195465087890625, 0.0258331298828125, -0.02069091796875, 0.03564453125, -0.049285888671875, 0.01837158203125, 0.0105743408203125, 0.0362548828125, 0.0030574798583984375, 0.0280609130859375, 0.032135009765625, -0.044097900390625, 0.01277923583984375, 0.01558685302734375, 0.010162353515625, -0.0266571044921875, 0.00951385498046875, 0.043243408203125, 0.010498046875, 0.0009036064147949219, 0.039825439453125, -0.0277099609375, -0.0184326171875, -0.0119171142578125, -0.0211181640625, 0.0011882781982421875, 0.00655364990234375, 0.021881103515625, -0.050079345703125, -0.0296783447265625, -0.0027675628662109375, 0.0030364990234375, 0.00739288330078125, -0.016387939453125, -0.0188140869140625, -0.030975341796875, -0.0005235671997070312, 0.0014715194702148438, 0.00936126708984375, 0.00827789306640625, 0.003314971923828125, -0.060150146484375, 0.0167388916015625, -0.0286712646484375, -0.0007123947143554688, -0.00025582313537597656, -0.0178985595703125, -0.00429534912109375, -0.0013523101806640625, 0.0225067138671875, 0.0086212158203125, 0.0272064208984375, 0.037384033203125, 0.0003037452697753906, -0.049652099609375, -0.0272979736328125, -0.02825927734375, 0.00957489013671875, 0.0055694580078125, -0.01544189453125, 0.01369476318359375, 0.0303955078125, -0.00969696044921875, -0.04425048828125, -0.002979278564453125, 0.016143798828125, 0.014862060546875, 0.027801513671875, -0.001865386962890625, -0.01483154296875, -0.003643035888671875, 0.00036907196044921875, 0.00223541259765625, 0.0062103271484375, -0.02349853515625, -0.01342010498046875, -0.0256500244140625, 0.034942626953125, -0.0023479461669921875, -0.007137298583984375, 0.006626129150390625, -0.0092315673828125, 0.006053924560546875, 0.044281005859375, 0.017913818359375, -0.03204345703125, -0.0237274169921875, -0.01216888427734375, -0.008819580078125, 0.03228759765625, 0.01216888427734375, -0.00466156005859375, 0.0069427490234375, -0.026824951171875, -0.020416259765625, 0.029388427734375, -0.00827789306640625, -0.01090240478515625, 0.025970458984375, -0.00951385498046875, 0.0293426513671875, 0.0005269050598144531, -0.0074005126953125, 0.0003409385681152344, 0.0176849365234375, 0.01512908935546875, 0.00310516357421875, 0.028411865234375, -0.0205535888671875, -0.050201416015625, -0.0054779052734375, -0.00298309326171875, -0.016265869140625, -0.01467132568359375, 0.006198883056640625, -0.045684814453125, -0.007289886474609375, 0.0064697265625, -0.029266357421875, -0.002552032470703125, -0.01087188720703125, 0.007053375244140625, 0.00206756591796875, 0.03900146484375, 0.0043182373046875, -0.017181396484375, 0.012939453125, 0.0018396377563476562, -0.0184783935546875, 0.0132293701171875, -0.02264404296875, -0.0191497802734375, 0.01629638671875, 0.03057861328125, 0.0053558349609375, -0.01739501953125, 0.0194549560546875, -0.036102294921875, -0.0318603515625, 0.01229095458984375, 0.019378662109375, 0.00768280029296875, -0.0099029541015625, 0.0010280609130859375, 0.0216522216796875, -0.0110015869140625, -0.01580810546875, 0.038330078125, 0.006481170654296875, -0.001102447509765625, 0.0254669189453125, 0.01739501953125, 0.0017423629760742188, 0.0087738037109375, 0.0086212158203125, -0.03363037109375, -0.0014657974243164062, -0.021575927734375, 0.0126190185546875, -0.0142974853515625, -0.048675537109375, -0.0311431884765625, -0.005130767822265625, -0.0183258056640625, 0.0159149169921875, -0.00926971435546875, 0.03790283203125, -0.015655517578125, -0.06719970703125, -0.0177001953125, -0.034454345703125, -0.05450439453125, -0.04095458984375, 0.035247802734375, -0.003208160400390625, -0.028167724609375, 0.0067138671875, 0.00417327880859375, -0.0026111602783203125, -0.0198822021484375, 0.0113983154296875, -0.00965118408203125, 0.0013275146484375, -0.0240478515625, 0.03704833984375, 0.011871337890625, 0.01812744140625, -0.0043182373046875, -0.0185546875, 0.0258331298828125, 0.007671356201171875, 0.04327392578125, -0.02197265625, -0.008880615234375, 0.0179443359375, -0.0567626953125, 0.0230560302734375, 0.00970458984375, 0.0038242340087890625, -0.05133056640625, -0.0259246826171875, -0.035125732421875, -0.006397247314453125, -0.004726409912109375, -0.0242156982421875, -0.00856781005859375, 0.0013637542724609375, 0.00580596923828125, -0.011688232421875, -0.00977325439453125, 0.00827789306640625, 0.0307312011718

In [ ]:
qdrant.upsert(collection_name="news_qdrant",
              points=points)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [ ]:
import numpy as np
# DB 저장됐으니 이제 질문 날려보기!

def embed(texts):
    """텍스트 목록을 받아서 벡터 배열로 변환하는 함수. openai embedding을 사용해 문서 수 x 1536차원으로 변환"""

    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=texts
    )

    return np.array([item.embedding for item in response.data])

In [ ]:
question = "대출 정보에 대해서 알려줘"

query_vec = embed([question])[0]

result = qdrant.query_points(
    collection_name="news_qdrant",   # 아까 만든 collection과 이름 같아야
    query=query_vec.tolist(),
    limit=5
)

print(result)

points=[ScoredPoint(id=111, version=0, score=0.3627825727441777, payload={'제목': '월 10만원 저축하면 정부가 10만원 더…18일부터 청년내일저축계좌 모집', '카테고리': '경제'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=51, version=0, score=0.3620797837926796, payload={'제목': '은행 가계대출 반년간 9조 넘게 줄었다', '카테고리': '경제'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=120, version=0, score=0.3417419887667473, payload={'제목': '문과생도 IT 인재로 육성…취업률 59% ‘눈길’', '카테고리': '경제'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=130, version=0, score=0.3183405259790597, payload={'제목': '뉴스프라임 처음 집 사면 LTV 80%…하반기 달라지는 정책은', '카테고리': '경제'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=3, version=0, score=0.30419494012366255, payload={'제목': '오늘부터 유류세 인하 폭 확대…하반기 바뀌는 세제·금융 정책은', '카테고리': '경제'}, vector=None, shard_key=None, order_value=None)]

In [ ]:
for point in result.points:
    print(point.id)
    print(docs[point.id][:100]) # 해당 인덱스 가진 본문
    print(point.payload)    # 메타데이터들

111
보건복지부 제공 보건복지부는 저소득 청년에 저축액의 최대 3배까지 추가 적립해주는 청년내일저축계좌 가입자를 오는 18일부터 모집한다고 밝혔다 해당 제도는 월 10만원을 저축하면 정
{'제목': '월 10만원 저축하면 정부가 10만원 더…18일부터 청년내일저축계좌 모집', '카테고리': '경제'}
51
기사내용 요약 가계대출 잔액 699조6521억원 금리상승 자산시장 주춤 영향 하반기 규제 강화에 증가 전환 어려울 듯 서울 뉴시스 이주혜 기자 국내 주요 은행의 가계대출 잔액이 올
{'제목': '은행 가계대출 반년간 9조 넘게 줄었다', '카테고리': '경제'}
120
KBS 부산 앵커 문과를 나와 죄송합니다 라는 자조적 말이 유행할 정도로 문과생의 취업 문턱은 갈수록 높아지는 상황인데요 기업이 직접 가르쳐서 뽑는 식으로 비전공자들도 IT 회사
{'제목': '문과생도 IT 인재로 육성…취업률 59% ‘눈길’', '카테고리': '경제'}
130
방송 2022년 7월 1일 금 이슈오늘 진행 박진형 이나연 출연 윤석천 경제평론가 오늘부터 유류세율 인하폭이 확대됐고 생애 최초 구매자를 대상으로 한 주택담보대출비율도 완화됐습니다
{'제목': '뉴스프라임 처음 집 사면 LTV 80%…하반기 달라지는 정책은', '카테고리': '경제'}
3
img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오늘 1일 부터 유류세율 인하 폭이 확대됩니다 올해 3분기에는 생애최초 주택 구매 대출 규제도 완화
{'제목': '오늘부터 유류세 인하 폭 확대…하반기 바뀌는 세제·금융 정책은', '카테고리': '경제'}

### 실습
1. 구축하고 싶은 문서를 찾기
2. chromadb에 문서 적재하고
3. 질문에 답하는 RAG 시스템을 구축해보자!

In [ ]:
# 1. 데이터 가져오기
data_library = pd.read_csv("../data/전국도서관표준데이터.csv", encoding="cp949")
data_library = data_library[:200]
docs = data_library['휴관일'].tolist()

In [ ]:
# 2 chromadb 컬렉션 만들기
collection = embed_client.get_or_create_collection(
    name="library_collection",
    embedding_function=embeddings,
    configuration={'hnsw' : {"space" : "cosine"}}
)

In [ ]:
# 정보 뽑기
ids = data_library.index.astype(str).tolist()
metadata = data_library[['도서관명', '시도명', '시군구명']].to_dict('records')

# 컬렉션에 추가
collection.upsert(ids=ids, documents=docs, metadatas=metadata)  # id 잘 안넣으면 랜덤으로 하기 때문에 잘 지정해줘야?
collection.count()

200

In [ ]:
question = "경남 진해의 "

result = collection.query(query_texts=[question], n_results=5)  # 아까 1_RAG에서 우리가 구현했던 기능이 한줄로 구현됨
result